-- Seed sinossi del catalogo: 209 sinossi originali (2-3 frasi, senza spoiler), niente fonte esterna.
-- Idempotente: tocca solo righe con synopsis IS NULL, chiave title+year.
UPDATE `movies` SET `synopsis` = 'Due detective di una metropoli piovosa e marcia — il veterano Somerset a una settimana dalla pensione e l''impulsivo Mills appena arrivato — inseguono un serial killer che mette in scena i suoi omicidi secondo i sette peccati capitali. Ogni delitto è un sermone, e l''assassino ha in mente un finale che li riguarda da vicino.', `synopsis_source` = NULL WHERE `title` = 'Seven' AND `year` = 1995 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Neil McCauley, rapinatore metodico che non si lega a nulla da cui non possa uscire in trenta secondi, prepara l''ultimo grande colpo a Los Angeles. Sulle sue tracce c''è Vincent Hanna, detective tanto brillante quanto divorato dal lavoro: due professionisti speculari, destinati a rispettarsi e a scontrarsi.', `synopsis_source` = NULL WHERE `title` = 'Heat - La sfida' AND `year` = 1995 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Cinque criminali si conoscono in una cella di custodia e organizzano insieme un colpo, ma l''affare li trascina verso un misterioso burattinaio di cui tutti hanno terrore: Keyser Söze. L''unico sopravvissuto a una strage al porto racconta la storia agli inquirenti, un tassello alla volta.', `synopsis_source` = NULL WHERE `title` = 'I soliti sospetti' AND `year` = 1995 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Woody, cowboy di pezza e giocattolo preferito di Andy, vede il suo posto minacciato dall''arrivo di Buzz Lightyear, space ranger convinto di essere un vero eroe spaziale. Rivali per gelosia, i due finiscono persi nel mondo esterno e devono allearsi per tornare a casa prima del trasloco.', `synopsis_source` = NULL WHERE `title` = 'Toy Story' AND `year` = 1995 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Scozia, XIII secolo. William Wallace, contadino che voleva solo una vita tranquilla, si trasforma in capo della rivolta contro l''occupazione inglese di Edoardo I dopo che la corona gli strappa l''amore e la pace. La sua guerra per la libertà diventa leggenda.', `synopsis_source` = NULL WHERE `title` = 'Braveheart' AND `year` = 1995 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un venditore d''auto pieno di debiti fa rapire la propria moglie per spartirsi il riscatto del ricco suocero, ma il piano frana subito in una scia di sangue nella neve del Minnesota. A ricomporre i pezzi c''è Marge Gunderson, poliziotta incinta e inesorabilmente gentile.', `synopsis_source` = NULL WHERE `title` = 'Fargo' AND `year` = 1996 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Edimburgo, anni Novanta: Renton e i suoi amici tossicodipendenti vivono di espedienti, euforia chimica e autodistruzione. Tra tentativi di disintossicazione e ricadute, Renton cerca una via d''uscita da amici che sono anche la sua rovina — scegliere la vita, dice, ma non è così semplice.', `synopsis_source` = NULL WHERE `title` = 'Trainspotting' AND `year` = 1996 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il 2 luglio astronavi gigantesche si piazzano sopra le principali città del mondo; il 3 luglio aprono il fuoco. Un pilota di caccia, un tecnico informatico e il presidente degli Stati Uniti guidano il contrattacco dell''umanità in vista del 4 luglio.', `synopsis_source` = NULL WHERE `title` = 'Independence Day' AND `year` = 1996 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Southampton, 1912: Jack, squattrinato con il biglietto vinto a poker, e Rose, ragazza dell''alta società promessa a un uomo che non ama, si incontrano sul transatlantico più famoso del mondo. Il loro amore attraversa le classi sociali mentre il Titanic corre verso il suo iceberg.', `synopsis_source` = NULL WHERE `title` = 'Titanic' AND `year` = 1997 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Guido, ebreo italiano pieno di fantasia, conquista la sua Dora e costruisce con lei e il figlio Giosuè una vita felice ad Arezzo. Quando la famiglia viene deportata, Guido trasforma il lager in un gioco a premi per proteggere il bambino dall''orrore.', `synopsis_source` = NULL WHERE `title` = 'La vita è bella' AND `year` = 1997 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Sheffield, ex città dell''acciaio: sei disoccupati senza arte né parte decidono di mettere in piedi uno spettacolo di spogliarello per raggranellare qualche sterlina. Tra prove goffe e dignità da ricostruire, il gruppo scopre che togliersi tutto è il modo più buffo di ritrovarsi.', `synopsis_source` = NULL WHERE `title` = 'Full Monty - Squattrinati organizzati' AND `year` = 1997 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un poliziotto newyorkese viene reclutato da un''agenzia segretissima che sorveglia gli alieni residenti sulla Terra. In completo nero e occhiali da sole, il novellino J e il veterano K devono ritrovare un congegno che fa gola a uno scarafaggio galattico, prima che la faccenda finisca in guerra interstellare.', `synopsis_source` = NULL WHERE `title` = 'Men in Black' AND `year` = 1997 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Los Angeles, anni Cinquanta: dietro la facciata patinata di Hollywood, tre poliziotti diversissimi — il duro Bud White, l''ambizioso Ed Exley e il mondano Jack Vincennes — indagano su una strage in una tavola calda. Il caso scoperchia una corruzione che arriva molto in alto.', `synopsis_source` = NULL WHERE `title` = 'L.A. Confidential' AND `year` = 1997 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il giovane guerriero Ashitaka, colpito da una maledizione, viaggia verso ovest e si ritrova nel mezzo della guerra tra la Città del Ferro di Lady Eboshi e gli dèi della foresta, al cui fianco combatte San, la principessa cresciuta dai lupi. Nessuno dei due fronti è davvero il cattivo: è questa la tragedia.', `synopsis_source` = NULL WHERE `title` = 'Principessa Mononoke' AND `year` = 1997 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Sbarco in Normandia: il capitano Miller riceve l''ordine di attraversare il fronte con la sua squadra per riportare a casa il soldato James Ryan, ultimo di quattro fratelli, gli altri tre caduti in guerra. Otto uomini rischiano la vita per salvarne uno, chiedendosi se ne valga la pena.', `synopsis_source` = NULL WHERE `title` = 'Salvate il soldato Ryan' AND `year` = 1998 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Truman Burbank conduce una vita perfetta in una cittadina di mare perfetta — ed è l''unico a non sapere che tutto, moglie compresa, è il set del reality più visto del pianeta. Quando piccole crepe incrinano la messinscena, Truman comincia a dubitare del suo mondo.', `synopsis_source` = NULL WHERE `title` = 'The Truman Show' AND `year` = 1998 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Drugo Lebowski, pigro cultore del White Russian, viene scambiato per un miliardario omonimo e coinvolto in un rapimento con riscatto insieme all''irascibile amico Walter. Ogni suo tentativo di semplificare le cose le complica gloriosamente, tra nichilisti, tappeti rovinati e partite a bowling.', `synopsis_source` = NULL WHERE `title` = 'Il grande Lebowski' AND `year` = 1998 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Quattro amici londinesi perdono una fortuna in una partita di carte truccata e hanno una settimana per ripagare un boss del porno. Il piano — derubare i vicini criminali — innesca un domino di malviventi, fucili antichi ed erba pregiata dove ogni pedina ignora le altre.', `synopsis_source` = NULL WHERE `title` = 'Lock & Stock - Pazzi scatenati' AND `year` = 1998 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il programmatore Thomas Anderson, hacker col nome di Neo, scopre che la realtà è una simulazione costruita dalle macchine per tenere addormentata l''umanità. Guidato da Morpheus e da Trinity, deve decidere se essere l''Eletto in grado di piegare le regole della Matrice.', `synopsis_source` = NULL WHERE `title` = 'Matrix' AND `year` = 1999 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un impiegato insonne e anestetizzato dal consumismo incontra Tyler Durden, venditore di sapone carismatico e anarchico, e con lui fonda un club clandestino dove gli uomini si picchiano per sentirsi vivi. Il progetto cresce, si radicalizza e sfugge a ogni controllo.', `synopsis_source` = NULL WHERE `title` = 'Fight Club' AND `year` = 1999 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il piccolo Cole confessa allo psicologo infantile Malcolm Crowe il suo segreto: vede i morti, ovunque, e ne è terrorizzato. Malcolm, reduce da un fallimento professionale che lo ossessiona, cerca di aiutarlo a convivere con il dono.', `synopsis_source` = NULL WHERE `title` = 'Il sesto senso' AND `year` = 1999 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Lester Burnham, quarantenne in piena crisi, molla il lavoro e ricomincia a desiderare, scandalizzando la moglie in carriera e la figlia adolescente. Dietro le siepi curate del sobborgo americano, ogni personaggio nasconde una vita segreta pronta a esplodere.', `synopsis_source` = NULL WHERE `title` = 'American Beauty' AND `year` = 1999 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Nel braccio della morte di un penitenziario della Louisiana arriva John Coffey, gigante mite condannato per un crimine atroce, che si rivela capace di miracoli. Il capo delle guardie Paul Edgecomb si trova davanti a un dilemma che lo accompagnerà per tutta la vita.', `synopsis_source` = NULL WHERE `title` = 'Il miglio verde' AND `year` = 1999 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il generale Massimo, tradito dal nuovo imperatore Commodo che gli ha sterminato la famiglia, finisce schiavo e poi gladiatore. Arena dopo arena risale fino al Colosseo, dove lo aspetta la vendetta davanti al popolo di Roma.', `synopsis_source` = NULL WHERE `title` = 'Il gladiatore' AND `year` = 2000 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Leonard soffre di amnesia anteriore: dimentica tutto nel giro di minuti e insegue l''assassino della moglie affidandosi a polaroid, appunti e tatuaggi. Il film ricostruisce la sua caccia a ritroso, lasciando lo spettatore nella sua stessa nebbia.', `synopsis_source` = NULL WHERE `title` = 'Memento' AND `year` = 2000 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un diamante da 86 carati rubato ad Anversa attira su Londra pugili gitani, allibratori, gangster russi e rapinatori improvvisati. In mezzo, un promoter di boxe clandestina che deve piazzare sul ring uno zingaro imbattibile e incomprensibile.', `synopsis_source` = NULL WHERE `title` = 'Snatch - Lo strappo' AND `year` = 2000 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Chuck Noland, analista FedEx che vive con il cronometro in mano, sopravvive a un incidente aereo e resta solo su un''isola deserta del Pacifico. Quattro anni di silenzio, ingegno e un pallone da volley di nome Wilson gli cambiano la misura di ogni cosa.', `synopsis_source` = NULL WHERE `title` = 'Cast Away' AND `year` = 2000 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Cina imperiale: la spada leggendaria Destino Verde viene rubata, e i due guerrieri Li Mu Bai e Yu Shu Lien — legati da un amore mai dichiarato — ne seguono le tracce fino alla giovane e indomabile Jen. Duelli sospesi tra i tetti e sui rami di bambù, e desideri repressi più taglienti delle lame.', `synopsis_source` = NULL WHERE `title` = 'La tigre e il dragone' AND `year` = 2000 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Quattro vite a Coney Island inseguono ciascuna il proprio sogno chimico: l''eroina per Harry, Marion e Tyrone, le anfetamine da dieta per la madre Sara, ipnotizzata dal miraggio della televisione. Le quattro parabole precipitano insieme in uno dei finali più duri del cinema.', `synopsis_source` = NULL WHERE `title` = 'Requiem for a Dream' AND `year` = 2000 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Amélie, cameriera parigina dall''immaginazione traboccante, decide di aggiustare di nascosto le vite degli altri con piccoli congegni di felicità. Quando trova l''album fotografico di uno sconosciuto gentile, tocca a lei rischiare: il più difficile dei suoi piani è farsi trovare.', `synopsis_source` = NULL WHERE `title` = 'Il favoloso mondo di Amélie' AND `year` = 2001 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'L''Anello del Potere, forgiato dall''Oscuro Signore Sauron, finisce nelle mani dello hobbit Frodo Baggins. Con una compagnia di nove — hobbit, uomini, un mago, un elfo e un nano — parte verso Mordor, l''unico luogo dove l''Anello può essere distrutto.', `synopsis_source` = NULL WHERE `title` = 'Il Signore degli Anelli - La Compagnia dell''Anello' AND `year` = 2001 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'All''orfano Harry Potter, cresciuto sotto la scala dei perfidi zii, viene rivelato l''undicesimo compleanno che è un mago, e famoso. A Hogwarts, tra pozioni, quidditch e amicizie che dureranno sette anni, scopre che il suo destino è legato al mago oscuro che gli uccise i genitori.', `synopsis_source` = NULL WHERE `title` = 'Harry Potter e la pietra filosofale' AND `year` = 2001 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'L''orco Shrek vuole solo la pace della sua palude, invasa dalle creature delle fiabe sfrattate da Lord Farquaad. Per riaverla accetta di liberare la principessa Fiona da una torre sorvegliata da un drago, in coppia con un ciuchino che non tace mai. La favola, da lì, va tutta storta nel modo giusto.', `synopsis_source` = NULL WHERE `title` = 'Shrek' AND `year` = 2001 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il matematico John Nash, genio schivo di Princeton, rivoluziona la teoria dei giochi mentre la sua mente comincia a tradirlo: la schizofrenia gli confonde realtà e delirio. La sua battaglia, sostenuta dalla moglie Alicia, arriverà fino al Nobel.', `synopsis_source` = NULL WHERE `title` = 'A Beautiful Mind' AND `year` = 2001 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Lo psicanalista Giovanni perde il figlio in un incidente subacqueo e la sua famiglia si sgretola nel silenzio del dolore. Una lettera inattesa della ragazza del figlio apre uno spiraglio in cui il lutto può cominciare a respirare.', `synopsis_source` = NULL WHERE `title` = 'La stanza del figlio' AND `year` = 2001 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Una donna esce senza memoria da un incidente su Mulholland Drive e viene raccolta da Betty, aspirante attrice appena arrivata a Hollywood piena di sogni. Le loro indagini sull''identità perduta scivolano in un labirinto onirico dove la città dei sogni mostra il suo rovescio.', `synopsis_source` = NULL WHERE `title` = 'Mulholland Drive' AND `year` = 2001 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'La decenne Chihiro, in viaggio con i genitori verso la nuova casa, finisce in un mondo di spiriti dove mamma e papà vengono trasformati in maiali. Per salvarli lavora nelle terme della strega Yubaba, difendendo il proprio nome e trovando un alleato nel misterioso Haku.', `synopsis_source` = NULL WHERE `title` = 'La città incantata' AND `year` = 2001 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Donnie, adolescente sonnambulo di provincia, sfugge per caso a un incidente assurdo e comincia a ricevere visite da Frank, un coniglio gigante che gli annuncia la fine del mondo entro 28 giorni. Tra fisica dei viaggi nel tempo e satira della provincia americana, il conto alla rovescia scorre.', `synopsis_source` = NULL WHERE `title` = 'Donnie Darko' AND `year` = 2001 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Varsavia, 1939: il pianista ebreo Władysław Szpilman vede la sua città e la sua famiglia inghiottite dal ghetto e dalle deportazioni. Sopravvive nascosto tra le rovine, aggrappato alla musica come ultima forma di dignità.', `synopsis_source` = NULL WHERE `title` = 'Il pianista' AND `year` = 2002 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Nella Cidade de Deus, favela di Rio, crescono insieme Buscapé, che sogna la fotografia, e Zé Pequeno, che sogna il trono dello spaccio. Vent''anni di guerre tra bande raccontati da chi è riuscito a guardarle attraverso un obiettivo.', `synopsis_source` = NULL WHERE `title` = 'City of God - La città di Dio' AND `year` = 2002 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'La Compagnia si è divisa: Frodo e Sam proseguono verso Mordor guidati dall''ambiguo Gollum, mentre Aragorn, Legolas e Gimli soccorrono il regno di Rohan minacciato da Saruman. Tutto converge verso la battaglia del Fosso di Helm.', `synopsis_source` = NULL WHERE `title` = 'Il Signore degli Anelli - Le due torri' AND `year` = 2002 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Frank Abagnale Jr., adolescente con un talento mostruoso per la truffa, incassa milioni spacciandosi per pilota, medico e avvocato. Alle sue calcagna, per anni, l''agente FBI Carl Hanratty: tra i due nasce un inseguimento che somiglia a un''adozione.', `synopsis_source` = NULL WHERE `title` = 'Prova a prendermi' AND `year` = 2002 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'L''Anello è sempre più pesante e Frodo sempre più solo, mentre gli eserciti di Sauron marciano su Minas Tirith. Aragorn deve accettare il proprio destino di re per dare alla Terra di Mezzo un''ultima possibilità.', `synopsis_source` = NULL WHERE `title` = 'Il Signore degli Anelli - Il ritorno del re' AND `year` = 2003 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Bob, star del cinema in trasferta pubblicitaria, e Charlotte, giovane moglie lasciata sola in albergo, si incontrano nelle notti insonni di Tokyo. Tra karaoke e conversazioni sussurrate nasce un''intimità sospesa che non ha bisogno di nome.', `synopsis_source` = NULL WHERE `title` = 'Lost in Translation - L''amore tradotto' AND `year` = 2003 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'La Sposa si risveglia dal coma quattro anni dopo il massacro del suo matrimonio e stila la lista: i membri della Squadra Assassina Vipera Mortale, e in cima Bill. Il primo volume è un crescendo di vendette, dal Giappone di O-Ren Ishii in poi.', `synopsis_source` = NULL WHERE `title` = 'Kill Bill: Volume 1' AND `year` = 2003 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il pesce pagliaccio Marlin, padre iperprotettivo, attraversa l''oceano per ritrovare il figlio Nemo, finito nell''acquario di un dentista di Sydney. Con lui c''è Dory, chirurgo blu senza memoria a breve termine e con una fiducia infinita.', `synopsis_source` = NULL WHERE `title` = 'Alla ricerca di Nemo' AND `year` = 2003 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Oh Dae-su viene rapito e rinchiuso per quindici anni in una stanza senza sapere perché; poi, un giorno, viene liberato con soldi, un telefono e cinque giorni per scoprire chi l''ha imprigionato. La verità è una trappola più crudele della cella.', `synopsis_source` = NULL WHERE `title` = 'Old Boy' AND `year` = 2003 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Dai giorni dell''alluvione di Firenze del 1966 agli anni Duemila, i fratelli Nicola e Matteo Carati prendono strade opposte — la psichiatria e l''utopia l''uno, la divisa e il tormento l''altro. Quarant''anni di storia italiana attraversati da una famiglia.', `synopsis_source` = NULL WHERE `title` = 'La meglio gioventù' AND `year` = 2003 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Joel scopre che Clementine, l''amore appena finito, ha fatto cancellare ogni ricordo di lui da una clinica specializzata, e per ripicca si sottopone allo stesso trattamento. Ma a metà procedura, dentro la sua testa, decide che quei ricordi vuole tenerseli.', `synopsis_source` = NULL WHERE `title` = 'Se mi lasci ti cancello' AND `year` = 2004 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Frankie Dunn, vecchio allenatore di boxe che non si perdona nulla, accetta controvoglia di allenare Maggie, cameriera trentenne testarda come poche. Insieme arrivano più in alto di quanto sognassero, fino a una scelta che nessun angolo del ring può preparare.', `synopsis_source` = NULL WHERE `title` = 'Million Dollar Baby' AND `year` = 2004 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'I supereroi sono stati messi fuori legge e Bob Parr, ex Mr. Incredible, ingrassa in un cubicolo assicurativo sognando i vecchi tempi. Una missione segreta lo riporta in azione — e trascina tutta la famiglia, superpoteri compresi, in una battaglia vera.', `synopsis_source` = NULL WHERE `title` = 'Gli Incredibili' AND `year` = 2004 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Titta Di Girolamo vive da otto anni in un albergo svizzero, senza qualità apparenti e con una valigia di soldi della mafia da depositare a scadenze regolari. Un gesto gentile verso la barista Sofia incrina la sua liturgia e gli costa carissimo.', `synopsis_source` = NULL WHERE `title` = 'Le conseguenze dell''amore' AND `year` = 2004 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Sophie, cappellaia diciottenne trasformata in vecchia da un sortilegio, trova rifugio nel castello semovente del mago Howl, vanitoso e sfuggente. Tra una guerra assurda e un demone del fuoco chiacchierone, il maleficio si scioglie dove nessuno guardava: nel cuore.', `synopsis_source` = NULL WHERE `title` = 'Il castello errante di Howl' AND `year` = 2004 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Bruce Wayne, orfano miliardario di Gotham, gira il mondo per capire la paura e torna a casa per rivoltarla contro i criminali. Con maschera, mantello e i gadget di Lucius Fox nasce Batman, mentre in città maturano il terrore dello Spaventapasseri e un piano per distruggerla.', `synopsis_source` = NULL WHERE `title` = 'Batman Begins' AND `year` = 2005 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Wyoming, 1963: i mandriani Ennis e Jack passano un''estate a guardia delle pecore su Brokeback Mountain e scoprono un amore che non sanno nominare. Per vent''anni se lo porteranno dietro, tra matrimoni di facciata e fughe in montagna, in un''America che non perdona.', `synopsis_source` = NULL WHERE `title` = 'I segreti di Brokeback Mountain' AND `year` = 2005 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'In un''Inghilterra distopica governata da un regime totalitario, un vendicatore mascherato da Guy Fawkes che si fa chiamare V dichiara guerra al potere a colpi di esplosivi e retorica. La giovane Evey, salvata per caso, viene trascinata nella sua rivoluzione.', `synopsis_source` = NULL WHERE `title` = 'V per Vendetta' AND `year` = 2005 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Willy Wonka, cioccolatiere geniale e recluso, nasconde cinque biglietti d''oro nelle sue tavolette: i bambini che li trovano visiteranno la fabbrica più segreta del mondo. Il piccolo Charlie, povero e gentile, è l''unico a non meritare una lezione.', `synopsis_source` = NULL WHERE `title` = 'La fabbrica di cioccolato' AND `year` = 2005 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'La polizia di Boston infiltra il giovane Billy Costigan nella gang del boss Frank Costello, mentre Costello ha piazzato da anni il suo uomo, Colin Sullivan, dentro la polizia. Due talpe speculari si cercano a vicenda, sapendo che il primo scoperto muore.', `synopsis_source` = NULL WHERE `title` = 'The Departed - Il bene e il male' AND `year` = 2006 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Spagna, 1944: mentre il patrigno falangista dà la caccia ai partigiani, la piccola Ofelia scopre un labirinto e un fauno che le affida tre prove per tornare principessa di un regno sotterraneo. Fiaba nera e guerra si specchiano senza sconti.', `synopsis_source` = NULL WHERE `title` = 'Il labirinto del fauno' AND `year` = 2006 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Berlino Est, 1984: il capitano della Stasi Wiesler sorveglia un drammaturgo e la sua compagna attrice, microfoni in ogni stanza. Ascoltando le loro vite, l''uomo grigio del regime comincia a proteggerli invece di denunciarli.', `synopsis_source` = NULL WHERE `title` = 'Le vite degli altri' AND `year` = 2006 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Londra vittoriana: i prestigiatori Angier e Borden, ex compagni divisi da una tragedia, si sfidano a colpi di numeri sempre più pericolosi. L''ossessione per il trucco perfetto — ''Il Trasporto Umano'' — li spinge oltre ogni sacrificio.', `synopsis_source` = NULL WHERE `title` = 'The Prestige' AND `year` = 2006 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Sei membri di una famiglia disfunzionale attraversano mezzo paese su un pulmino Volkswagen scassato per portare la piccola Olive a un concorso di bellezza per bambine. Ogni chilometro perde un pezzo di motore e aggiunge un pezzo di verità.', `synopsis_source` = NULL WHERE `title` = 'Little Miss Sunshine' AND `year` = 2006 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Andy, aspirante giornalista fresca di laurea, diventa assistente di Miranda Priestly, direttrice di una rivista di moda tanto leggendaria quanto spietata. Sopravvivere al suo tritacarne significa capire quanto di sé è disposta a cedere.', `synopsis_source` = NULL WHERE `title` = 'Il diavolo veste Prada' AND `year` = 2006 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Prima missione da 007 per James Bond: fermare Le Chiffre, banchiere del terrorismo internazionale, battendolo in una partita di poker milionaria al Casino Royale del Montenegro. Al suo fianco Vesper Lynd, la donna che gli cambierà per sempre le regole.', `synopsis_source` = NULL WHERE `title` = 'Casino Royale' AND `year` = 2006 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Borat Sagdiyev, giornalista kazako trasandato e irresistibile, attraversa gli Stati Uniti per un documentario e per sposare Pamela Anderson. Le sue interviste a americani veri, ignari dello scherzo, mettono a nudo il paese meglio di qualunque inchiesta.', `synopsis_source` = NULL WHERE `title` = 'Borat' AND `year` = 2006 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Roma, estate 1989: Luca scopre alla vigilia della maturità che il professore più temuto d''Italia, il carogna Martinelli, è il suo commissario d''esame. Tra ripetizioni, amori e notti in vespa, l''ultima estate da liceale diventa quella che non si dimentica.', `synopsis_source` = NULL WHERE `title` = 'Notte prima degli esami' AND `year` = 2006 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un cacciatore trova nel deserto texano i resti di uno scambio di droga finito male e una valigetta con due milioni di dollari, e se la porta via. Sulle sue tracce si mette Anton Chigurh, killer con un compressore d''aria e una moneta che decide chi vive; a guardare le macerie, lo sceriffo Bell.', `synopsis_source` = NULL WHERE `title` = 'Non è un paese per vecchi' AND `year` = 2007 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Daniel Plainview, cercatore di petrolio spietato e magnetico, costruisce il suo impero nella California di inizio Novecento, trascinandosi dietro un figlio adottivo e un duello personale con il giovane predicatore Eli Sunday. L''avidità come vangelo, fino all''ultima goccia.', `synopsis_source` = NULL WHERE `title` = 'Il petroliere' AND `year` = 2007 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Christopher McCandless, neolaureato di buona famiglia, dona i risparmi in beneficenza, brucia i documenti e sparisce verso l''Alaska in cerca di una vita autentica. Il suo viaggio ai margini dell''America è punteggiato di incontri che gli vogliono bene.', `synopsis_source` = NULL WHERE `title` = 'Into the Wild - Nelle terre selvagge' AND `year` = 2007 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Remy, topo di campagna con un palato sopraffino, sogna di cucinare come il suo idolo Gusteau. A Parigi stringe un patto segreto con Linguini, sguattero imbranato: lui ai fornelli — nascosto sotto il cappello — e la Francia intera da conquistare.', `synopsis_source` = NULL WHERE `title` = 'Ratatouille' AND `year` = 2007 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Juno, sedicenne dalla battuta fulminante, resta incinta dell''amico Paulie e decide di portare avanti la gravidanza dando il bambino in adozione a una coppia perfetta trovata sugli annunci. Nove mesi per scoprire che gli adulti non sono più pronti di lei.', `synopsis_source` = NULL WHERE `title` = 'Juno' AND `year` = 2007 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Batman, il commissario Gordon e il procuratore Harvey Dent stanno strangolando il crimine di Gotham quando arriva il Joker, terrorista senza movente che vuole solo veder bruciare il mondo. Le sue trappole morali costringono ognuno a scegliere che cosa è disposto a diventare.', `synopsis_source` = NULL WHERE `title` = 'Il cavaliere oscuro' AND `year` = 2008 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Sulla Terra sommersa dai rifiuti, il piccolo robot WALL·E compatta spazzatura da settecento anni, collezionando tesori e solitudine. L''arrivo della sonda EVE lo trascina in un viaggio spaziale che può riportare a casa l''umanità impigrita.', `synopsis_source` = NULL WHERE `title` = 'WALL·E' AND `year` = 2008 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Walt Kowalski, reduce di Corea vedovo e razzista, ringhia contro i vicini hmong finché il giovane Thao non tenta di rubargli la Gran Torino per un''iniziazione di gang. Da quella colpa nasce un''improbabile adozione — e un''ultima, lucidissima scelta.', `synopsis_source` = NULL WHERE `title` = 'Gran Torino' AND `year` = 2008 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Jamal, ragazzo degli slum di Mumbai, è a una domanda dal montepremi di ''Chi vuol essere milionario'' e la polizia lo tortura convinta che bari. Ogni risposta, spiega lui, è un pezzo della sua vita — e tutte portano ad Latika, l''amore perso e ritrovato.', `synopsis_source` = NULL WHERE `title` = 'The Millionaire' AND `year` = 2008 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Cinque storie dentro il sistema camorristico campano: i ragazzini che sognano Scarface, il sarto che lavora per le griffe, il contabile che porta i soldi ai clan, i rifiuti tossici sotterrati nelle campagne. Nessuna redenzione, solo il sistema.', `synopsis_source` = NULL WHERE `title` = 'Gomorra' AND `year` = 2008 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Giulio Andreotti, sette volte presidente del Consiglio, attraversa impassibile processi, misteri e morti eccellenti della Prima Repubblica. Sorrentino lo ritrae come una sfinge notturna e ironica, tra emicranie e preghiere.', `synopsis_source` = NULL WHERE `title` = 'Il divo' AND `year` = 2008 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Due sicari irlandesi, il tormentato Ray e il paterno Ken, vengono spediti a ''raffreddarsi'' a Bruges dopo un lavoro finito malissimo. Tra canali medievali e sensi di colpa, l''ordine che arriva dal capo Harry trasforma la cartolina in tragedia morale.', `synopsis_source` = NULL WHERE `title` = 'In Bruges - La coscienza dell''assassino' AND `year` = 2008 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Alla morte della nonna, la famiglia Graham comincia a disgregarsi tra lutti, segreti ereditati e presenze che nessuno vuole nominare. Quello che sembra un dramma sul dolore si rivela, pezzo dopo pezzo, un incubo sul destino.', `synopsis_source` = NULL WHERE `title` = 'Hereditary - Le radici del male' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Francia occupata: mentre il tenente Aldo Raine e i suoi Bastardi scalpano nazisti, la giovane ebrea Shosanna, unica sopravvissuta della sua famiglia, gestisce un cinema parigino dove il Reich vuole celebrare una première. Due piani di vendetta convergono sulla stessa sala.', `synopsis_source` = NULL WHERE `title` = 'Bastardi senza gloria' AND `year` = 2009 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il marine paraplegico Jake Sully arriva su Pandora per guidare un avatar Na''vi e guadagnarsi la fiducia del popolo indigeno, mentre la compagnia mineraria umana scalpita per l''unobtainium sotto i loro alberi. Jake impara il mondo che dovrebbe tradire.', `synopsis_source` = NULL WHERE `title` = 'Avatar' AND `year` = 2009 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il vedovo Carl Fredricksen lega migliaia di palloncini alla casa e vola verso le cascate del Sud America, promessa mai mantenuta alla moglie Ellie. A bordo, clandestino, c''è Russell, esploratore di otto anni: l''avventura che Carl non aveva previsto.', `synopsis_source` = NULL WHERE `title` = 'Up' AND `year` = 2009 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'A Johannesburg, dove un''astronave carica di alieni derelitti galleggia da vent''anni sopra un campo profughi, il burocrate Wikus van der Merwe viene contaminato durante uno sgombero e comincia a trasformarsi. L''unico posto dove nascondersi è il Distretto 9.', `synopsis_source` = NULL WHERE `title` = 'District 9' AND `year` = 2009 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il diciannovenne Malik entra in carcere analfabeta e senza protezioni; il clan còrso che comanda il penitenziario lo usa e lo istruisce. Sei anni dopo, il ragazzo delle commissioni ha imparato tutto — e ha un piano suo.', `synopsis_source` = NULL WHERE `title` = 'Il profeta' AND `year` = 2009 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il mattino dopo l''addio al celibato a Las Vegas, tre amici si svegliano in una suite devastata con una tigre in bagno, un neonato nell''armadio e nessun ricordo — e lo sposo è sparito. Devono ricostruire la notte prima del matrimonio.', `synopsis_source` = NULL WHERE `title` = 'Una notte da leoni' AND `year` = 2009 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Dom Cobb ruba segreti infilandosi nei sogni altrui, ma stavolta il compito è l''inverso: piantare un''idea nella mente di un erede industriale. Sogni dentro sogni, una squadra di specialisti e il fantasma della moglie Mal che sabota ogni livello.', `synopsis_source` = NULL WHERE `title` = 'Inception' AND `year` = 2010 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Harvard, 2003: Mark Zuckerberg trasforma una ripicca notturna in TheFacebook e in pochi anni nel social network planetario. Le due cause legali che lo inseguono — i gemelli Winklevoss e l''ex migliore amico Eduardo — raccontano il prezzo dell''impresa.', `synopsis_source` = NULL WHERE `title` = 'The Social Network' AND `year` = 2010 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Giorgio VI, balbuziente, sale al trono d''Inghilterra proprio quando la radio e la guerra esigono una voce. Il logopedista australiano Lionel Logue, coi suoi metodi irriverenti, diventa l''amico che il re non sapeva di potersi permettere.', `synopsis_source` = NULL WHERE `title` = 'Il discorso del re' AND `year` = 2010 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Andy parte per il college e i giocattoli finiscono per errore in un asilo che sembra un paradiso ed è un regime, governato dall''orsacchiotto Lotso. Woody e Buzz organizzano l''evasione più rocambolesca della loro vita di plastica.', `synopsis_source` = NULL WHERE `title` = 'Toy Story 3 - La grande fuga' AND `year` = 2010 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Nina, ballerina disciplinata fino all''autodistruzione, ottiene il doppio ruolo del Lago dei cigni: perfetta come cigno bianco, deve ancora trovare il nero. Tra una madre soffocante, una rivale sensuale e un coreografo manipolatore, la metamorfosi la divora.', `synopsis_source` = NULL WHERE `title` = 'Il cigno nero' AND `year` = 2010 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = '1954: l''agente federale Teddy Daniels sbarca sull''isola-manicomio di Shutter Island per indagare sulla scomparsa di una paziente. Tra uragano, esperimenti sussurrati e incubi ricorrenti, l''isola sembra costruita per non lasciarlo andare via.', `synopsis_source` = NULL WHERE `title` = 'Shutter Island' AND `year` = 2010 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Alberto, impiegato delle poste brianzolo, pur di ottenere il trasferimento a Milano finisce spedito in un paesino del Cilento, convinto di andare incontro all''inferno. Il Sud smonta un pregiudizio al giorno, finché il problema diventa tornare.', `synopsis_source` = NULL WHERE `title` = 'Benvenuti al Sud' AND `year` = 2010 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un giovane stuntman di Los Angeles arrotonda come autista per rapine: cinque minuti, non uno di più, il migliore in città. L''affetto per la vicina Irene e per suo figlio lo trascina in un colpo sbagliato, e la sua calma glaciale si rivela per quello che è.', `synopsis_source` = NULL WHERE `title` = 'Drive' AND `year` = 2011 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Philippe, ricco tetraplegico parigino, assume come badante Driss, ragazzo di banlieue appena uscito di prigione, proprio perché è l''unico che non lo tratta da malato. Ne nasce un''amicizia irriverente che rimette in moto entrambi.', `synopsis_source` = NULL WHERE `title` = 'Quasi amici' AND `year` = 2011 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Hollywood, 1927: George Valentin è il re del muto, ma l''avvento del sonoro lo cancella mentre lancia la stella di Peppy Miller, la comparsa che lo ha sempre amato. Un film muto e in bianco e nero sull''orgoglio e la riconoscenza.', `synopsis_source` = NULL WHERE `title` = 'The Artist' AND `year` = 2011 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Teheran: Nader e Simin si separano perché lei vuole emigrare e lui non può lasciare il padre malato di Alzheimer. L''assunzione di una badante religiosa innesca un incidente, una denuncia e un ingranaggio giudiziario dove ognuno ha le sue ragioni e i suoi segreti.', `synopsis_source` = NULL WHERE `title` = 'Una separazione' AND `year` = 2011 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Gil, sceneggiatore americano in vacanza a Parigi con una fidanzata che non lo capisce, a mezzanotte sale su un''auto d''epoca e sbuca negli anni Venti, tra Hemingway, Fitzgerald e Gertrude Stein. Ogni notte torna, finché la nostalgia non gli presenta il conto.', `synopsis_source` = NULL WHERE `title` = 'Midnight in Paris' AND `year` = 2011 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Texas, due anni prima della guerra civile: il cacciatore di taglie King Schultz libera lo schiavo Django e ne fa il suo socio. Obiettivo finale: Candyland, la piantagione dove è tenuta Broomhilda, la moglie di Django.', `synopsis_source` = NULL WHERE `title` = 'Django Unchained' AND `year` = 2012 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Otto anni dopo la morte di Harvey Dent, Gotham vive una pace fondata su una bugia e Bruce Wayne fa l''eremita. L''arrivo di Bane, mercenario mascherato che vuole compiere l''opera di Ra''s al Ghul, costringe un Batman arrugginito a risorgere — passando da un pozzo.', `synopsis_source` = NULL WHERE `title` = 'Il cavaliere oscuro - Il ritorno' AND `year` = 2012 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Teheran, 1979: sei diplomatici americani sfuggiti all''assalto dell''ambasciata si nascondono dal console canadese. La CIA li esfiltra con la copertura più assurda disponibile: fingere che siano la troupe di un film di fantascienza intitolato Argo.', `synopsis_source` = NULL WHERE `title` = 'Argo' AND `year` = 2012 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Loki arriva sulla Terra con un esercito alieno e il Tesseract, e Nick Fury gioca l''ultima carta: mettere nella stessa stanza Iron Man, Captain America, Thor, Hulk, Vedova Nera e Occhio di Falco. Prima che salvino il mondo devono smettere di litigare.', `synopsis_source` = NULL WHERE `title` = 'The Avengers' AND `year` = 2012 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Naufragato nel Pacifico, il sedicenne indiano Pi Patel divide una scialuppa con una tigre del Bengala chiamata Richard Parker. La loro traversata è una storia di sopravvivenza così straordinaria che alla fine viene offerta anche una versione più credibile: a ognuno la scelta.', `synopsis_source` = NULL WHERE `title` = 'Vita di Pi' AND `year` = 2012 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Georges e Anne, ottuagenari colti e ancora innamorati, vedono la loro vita parigina restringersi dopo l''ictus di lei. Haneke filma senza pietismi la devozione di lui, fino al gesto estremo che dà il titolo al film.', `synopsis_source` = NULL WHERE `title` = 'Amour' AND `year` = 2012 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un hard disk con le identità degli agenti NATO infiltrati è in mani ostili e Bond, dato per morto, torna in servizio malconcio. Il nemico è Silva, ex agente geniale con un conto personale da regolare con M: stavolta la partita è in casa.', `synopsis_source` = NULL WHERE `title` = 'Skyfall' AND `year` = 2012 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Jep Gambardella, re mondano di Roma, compie sessantacinque anni e da quarantatré non scrive il secondo romanzo. La notizia della morte del primo amore lo spinge a vagare tra feste, terrazze e rovine in cerca della grande bellezza — o almeno di uno stupore.', `synopsis_source` = NULL WHERE `title` = 'La grande bellezza' AND `year` = 2013 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'L''ascesa di Jordan Belfort da venditore di penny stock a re di Wall Street: soldi a palate, sedute collettive di eccessi, frodi come modello di business. L''FBI osserva, il narratore non si pente quasi mai, e il ritmo non rallenta un secondo.', `synopsis_source` = NULL WHERE `title` = 'The Wolf of Wall Street' AND `year` = 2013 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un incidente orbitale distrugge lo shuttle e lascia la dottoressa Ryan Stone sola nello spazio, con l''ossigeno che cala e i detriti che tornano a ogni orbita. Novanta minuti di sopravvivenza pura tra stazioni spaziali morenti, e una ragione per tornare a casa da trovare.', `synopsis_source` = NULL WHERE `title` = 'Gravity' AND `year` = 2013 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Solomon Northup, violinista nero libero di New York, viene drogato, rapito e venduto come schiavo nel Sud del 1841. Dodici anni di piantagioni, padroni e resistenza interiore, tratti dalla sua storia vera.', `synopsis_source` = NULL WHERE `title` = '12 anni schiavo' AND `year` = 2013 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Theodore, che scrive lettere d''amore per conto terzi ed è reduce da un divorzio, si innamora di Samantha, il suo nuovo sistema operativo dalla voce calda e dall''intelligenza che cresce di ora in ora. Una storia d''amore vera, con un solo corpo in due.', `synopsis_source` = NULL WHERE `title` = 'Her' AND `year` = 2013 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Due bambine spariscono il giorno del Ringraziamento e il padre di una, Keller Dover, decide che la polizia è troppo lenta: sequestra il principale sospettato e se ne occupa da sé. Il detective Loki indaga su entrambi i fronti, in un intreccio sempre più cupo.', `synopsis_source` = NULL WHERE `title` = 'Prisoners' AND `year` = 2013 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'La Terra muore tra tempeste di polvere e raccolti malati; l''ex pilota Cooper lascia i figli per guidare una spedizione oltre un wormhole, in cerca di un pianeta abitabile. Là fuori un''ora può costare sette anni, e l''amore risulta essere un dato quantificabile quanto la gravità.', `synopsis_source` = NULL WHERE `title` = 'Interstellar' AND `year` = 2014 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Le rocambolesche avventure di Gustave H., concierge leggendario di un grand hotel mitteleuropeo tra le due guerre, e del suo lobby boy Zero: un quadro rubato, un''eredità contesa, una fuga dal carcere. Wes Anderson impila cornici come pasticcini.', `synopsis_source` = NULL WHERE `title` = 'Grand Budapest Hotel' AND `year` = 2014 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Andrew, batterista diciannovenne del conservatorio, finisce nell''orchestra di Terence Fletcher, direttore che usa il terrore come metodo pedagogico. Sangue sui piatti, sedie che volano e una domanda: quanto costa diventare uno dei grandi?', `synopsis_source` = NULL WHERE `title` = 'Whiplash' AND `year` = 2014 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Riggan Thomson, ex divo cinematografico di un supereroe alato, punta tutto su un dramma a Broadway per dimostrare di valere qualcosa. Tra un attore geniale e insopportabile, una figlia appena disintossicata e la voce di Birdman nella testa, la première si avvicina in un unico, apparente piano sequenza.', `synopsis_source` = NULL WHERE `title` = 'Birdman' AND `year` = 2014 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il giorno del quinto anniversario, Amy Dunne scompare e il marito Nick diventa in fretta il sospettato perfetto per media e polizia. Ma il diario di Amy e la realtà non combaciano: il matrimonio era un gioco molto più feroce di come appariva.', `synopsis_source` = NULL WHERE `title` = 'L''amore bugiardo - Gone Girl' AND `year` = 2014 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Mason cresce davanti alla macchina da presa: Linklater ha filmato lo stesso cast per dodici anni, un pezzo all''anno, dai sei ai diciotto anni del protagonista. Traslochi, patrigni, primi amori — il tempo stesso è il film.', `synopsis_source` = NULL WHERE `title` = 'Boyhood' AND `year` = 2014 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'John Wick, leggendario sicario ritiratosi per amore, ha appena perso la moglie quando dei gangster russi gli rubano l''auto e gli uccidono il cucciolo che lei gli aveva lasciato. Errore fatale: il mondo criminale sa cosa succede quando Wick torna al lavoro.', `synopsis_source` = NULL WHERE `title` = 'John Wick' AND `year` = 2014 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Pietro, ricercatore di neurobiologia precario e brillante, viene tagliato dall''università e recluta altri cervelli in fuga interna — latinisti benzinai, chimici lavapiatti — per sintetizzare smart drug legali. La banda dei ricercatori diventa il cartello più colto di Roma.', `synopsis_source` = NULL WHERE `title` = 'Smetto quando voglio' AND `year` = 2014 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'In un deserto post-apocalittico dove acqua e benzina sono potere, l''Imperatrice Furiosa fugge dalla Cittadella con le cinque mogli-fattrici di Immortan Joe, che le scatena contro l''intera orda. Max, ex poliziotto ridotto a sacca di sangue ambulante, si ritrova nel mezzo dell''inseguimento più furioso mai filmato.', `synopsis_source` = NULL WHERE `title` = 'Mad Max: Fury Road' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = '1823: il cacciatore di pelli Hugh Glass viene sbranato da un grizzly e abbandonato agonizzante dai compagni, uno dei quali gli uccide il figlio. Glass si trascina per centinaia di chilometri di inverno americano con un solo pensiero a tenerlo vivo.', `synopsis_source` = NULL WHERE `title` = 'Revenant - Redivivo' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Creduto morto durante una tempesta, l''astronauta e botanico Mark Watney resta solo su Marte con provviste per pochi mesi e nessun contatto. Coltivare patate nel suolo marziano è solo il primo dei problemi da risolvere a colpi di scienza, mentre la NASA scopre che è vivo.', `synopsis_source` = NULL WHERE `title` = 'Sopravvissuto - The Martian' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'La squadra investigativa del Boston Globe, Spotlight, comincia a tirare un filo: un prete pedofilo protetto dalla diocesi. Il filo diventa un sistema — decine di preti, insabbiamenti, complicità cittadine — e il giornalismo fa il suo mestiere fino in fondo.', `synopsis_source` = NULL WHERE `title` = 'Il caso Spotlight' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Nella testa dell''undicenne Riley le emozioni — Gioia, Tristezza, Paura, Rabbia e Disgusto — lavorano in una plancia di comando. Il trasloco a San Francisco manda in tilt il sistema: Gioia e Tristezza si perdono nella memoria a lungo termine, e senza di loro Riley smette di sentire.', `synopsis_source` = NULL WHERE `title` = 'Inside Out' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il giovane programmatore Caleb vince una settimana nella tenuta isolata di Nathan, geniale e alcolico fondatore del motore di ricerca per cui lavora. Il compito: testare Ava, un''androide dallo sguardo troppo intelligente. Il test, ovviamente, funziona in entrambe le direzioni.', `synopsis_source` = NULL WHERE `title` = 'Ex Machina' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Trent''anni dopo la caduta dell''Impero, Luke Skywalker è scomparso e il Primo Ordine è sorto dalle ceneri imperiali. Rey, raccoglitrice di rottami su Jakku, incrocia il disertore Finn e il droide BB-8, custode della mappa che porta a Luke, e insieme a Han Solo si ritrova nella lotta della Resistenza contro Kylo Ren.', `synopsis_source` = NULL WHERE `title` = 'Star Wars: Il risveglio della Forza' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Wyoming, qualche anno dopo la guerra civile: una tormenta rinchiude in un emporio otto sconosciuti armati, tra cui un boia, una prigioniera e un paio di ex soldati. Nessuno è chi dice di essere, e Tarantino lascia che la stanza si saturi di polvere da sparo.', `synopsis_source` = NULL WHERE `title` = 'The Hateful Eight' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Enzo Ceccotti, piccolo delinquente di Tor Bella Monaca, cade nel Tevere in un bidone di scorie e ne esce con una forza sovrumana che usa per rapinare bancomat. Sarà Alessia, ragazza fragile ossessionata da Jeeg Robot, a pretendere che diventi un eroe.', `synopsis_source` = NULL WHERE `title` = 'Lo chiamavano Jeeg Robot' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'L''agente FBI Kate Macer viene aggregata a una task force ambigua che opera al confine col Messico contro i cartelli, guidata dal ciabattante Matt e dal silenzioso Alejandro. Più capisce le regole della missione, più scopre che le regole non ci sono.', `synopsis_source` = NULL WHERE `title` = 'Sicario' AND `year` = 2015 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Los Angeles: Mia fa la barista tra un provino umiliante e l''altro, Sebastian suona jazz nei locali sbagliati sognando un club tutto suo. Si innamorano ballando sulle colline, ma i sogni di ciascuno presentano il conto alla coppia.', `synopsis_source` = NULL WHERE `title` = 'La La Land' AND `year` = 2016 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Dodici astronavi aliene si posano mute sulla Terra e la linguista Louise Banks viene arruolata per decifrare la loro scrittura circolare. Capire la lingua degli eptapodi significa cambiare il proprio modo di percepire il tempo — con tutto ciò che ne consegue.', `synopsis_source` = NULL WHERE `title` = 'Arrival' AND `year` = 2016 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Lee Chandler, tuttofare solitario di Boston, deve tornare nella cittadina natale alla morte del fratello, che lo ha nominato tutore del nipote sedicenne. Manchester è il luogo della tragedia che Lee non si perdona, e il film ha il coraggio di non guarirlo.', `synopsis_source` = NULL WHERE `title` = 'Manchester by the Sea' AND `year` = 2016 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Sette amici a cena decidono per gioco di mettere i telefoni sul tavolo e leggere ad alta voce ogni messaggio in arrivo. Nel giro di una serata il gioco al massacro smonta coppie, amicizie e rispettabilità.', `synopsis_source` = NULL WHERE `title` = 'Perfetti sconosciuti' AND `year` = 2016 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Chiron cresce a Miami in tre atti — bambino silenzioso, adolescente braccato, adulto corazzato — tra una madre dipendente dal crack e la tenerezza inattesa di uno spacciatore e del suo amico Kevin. Un ritratto delicatissimo di mascolinità e identità.', `synopsis_source` = NULL WHERE `title` = 'Moonlight' AND `year` = 2016 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Ben Cash cresce i suoi sei figli in una foresta del Pacifico nord-occidentale: caccia, Chomsky, arrampicata e niente Coca-Cola. La morte della moglie lo costringe a portare la tribù in viaggio verso il funerale, dentro quell''America da cui era scappato.', `synopsis_source` = NULL WHERE `title` = 'Captain Fantastic' AND `year` = 2016 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Checco, quarantenne pugliese con il mito del posto fisso, pur di non firmare le dimissioni accetta trasferimenti sempre più estremi, fino al Polo Nord. Tra orsi bianchi e una ricercatrice che vive senza garanzie, il posto fisso incontra il suo peggior nemico: la felicità.', `synopsis_source` = NULL WHERE `title` = 'Quo vado?' AND `year` = 2016 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Mitsuha, liceale di un paesino di montagna, e Taki, studente di Tokyo, si svegliano a intermittenza l''uno nel corpo dell''altra senza essersi mai incontrati. Quando decidono di cercarsi, scoprono che tra loro non c''è solo distanza — c''è una cometa.', `synopsis_source` = NULL WHERE `title` = 'Your Name.' AND `year` = 2016 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Dunkerque, 1940: quattrocentomila soldati alleati intrappolati su una spiaggia sotto il tiro tedesco. Nolan intreccia tre tempi — una settimana sul molo, un giorno in mare sulle barche dei civili, un''ora in volo con gli Spitfire — in un meccanismo di pura tensione.', `synopsis_source` = NULL WHERE `title` = 'Dunkirk' AND `year` = 2017 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Los Angeles 2049: l''agente K, replicante che dà la caccia ai replicanti fuggiaschi, scopre i resti di un miracolo che potrebbe far crollare l''ordine del mondo. L''indagine lo porta da Deckard, sparito da trent''anni, e a una domanda sulla propria memoria.', `synopsis_source` = NULL WHERE `title` = 'Blade Runner 2049' AND `year` = 2017 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Estate 1983, campagna lombarda: Elio, diciassettenne colto e inquieto, vede arrivare nella villa di famiglia Oliver, il dottorando americano ospite del padre. Sei settimane di biciclette, albicocche e non detti che diventano il primo amore, quello che marchia.', `synopsis_source` = NULL WHERE `title` = 'Chiamami col tuo nome' AND `year` = 2017 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'A mesi dall''omicidio irrisolto della figlia, Mildred Hayes affitta tre cartelloni fuori città per accusare pubblicamente lo sceriffo Willoughby di non aver trovato il colpevole. Il gesto spacca la comunità di Ebbing e innesca una spirale di rabbia, colpa e inattesa grazia.', `synopsis_source` = NULL WHERE `title` = 'Tre manifesti a Ebbing, Missouri' AND `year` = 2017 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Baltimora, 1962: Elisa, addetta alle pulizie muta in un laboratorio governativo, scopre la creatura anfibia tenuta in catene per gli esperimenti della Guerra Fredda. Tra i due nasce un''intesa senza parole, e un piano di fuga.', `synopsis_source` = NULL WHERE `title` = 'La forma dell''acqua' AND `year` = 2017 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Chris, fotografo nero di New York, va a conoscere i genitori della fidanzata bianca nella loro villa suburbana, dove tutti sono accoglienti in modo leggermente sbagliato. Il weekend scivola dal disagio al terrore in una delle satire più affilate del decennio.', `synopsis_source` = NULL WHERE `title` = 'Scappa - Get Out' AND `year` = 2017 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Miguel, dodicenne messicano nato in una famiglia che ha bandito la musica, il giorno dei Morti finisce nella Terra dell''Aldilà. Per tornare a casa deve farsi benedire da un antenato — e scoprire la verità sul musicista che la famiglia ha cancellato.', `synopsis_source` = NULL WHERE `title` = 'Coco' AND `year` = 2017 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Derry, Maine: i bambini spariscono e la colpa è di It, entità che si nutre della paura e appare come il clown Pennywise. I sette ragazzini del Club dei Perdenti, ognuno con i propri terrori, decidono di affrontarlo nell''estate del 1989.', `synopsis_source` = NULL WHERE `title` = 'It' AND `year` = 2017 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Dalla Zanzibar coloniale ai palchi di Wembley: Farrokh Bulsara diventa Freddie Mercury e i Queen riscrivono le regole del rock tra geniali intuizioni in studio e attriti. Tutto converge verso i venti minuti del Live Aid 1985.', `synopsis_source` = NULL WHERE `title` = 'Bohemian Rhapsody' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Jackson Maine, rockstar in declino tra alcol e acufeni, scopre Ally in un drag bar e la trascina sul palco e nella sua vita. Mentre la stella di lei sale, quella di lui precipita: la versione più cruda della favola hollywoodiana più raccontata.', `synopsis_source` = NULL WHERE `title` = 'A Star Is Born' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Città del Messico, 1970-71: un anno nella casa borghese di Colonia Roma visto dagli occhi di Cleo, la domestica mixteca. Gravidanze, abbandoni e una strage di piazza si intrecciano nel bianco e nero autobiografico di Cuarón.', `synopsis_source` = NULL WHERE `title` = 'Roma' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = '1962: Tony Lip, buttafuori italoamericano dai modi spicci, viene assunto come autista da Don Shirley, raffinato pianista nero, per una tournée negli stati del Sud segregazionista. Il Green Book è la guida dei locali che accettano neri; il viaggio cambia entrambi.', `synopsis_source` = NULL WHERE `title` = 'Green Book' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Thanos, titano convinto che l''universo vada dimezzato per salvarlo, parte alla raccolta delle sei Gemme dell''Infinito. Tutti gli eroi Marvel — Avengers, Guardiani, Wakanda — combattono su più fronti la battaglia che per una volta possono perdere.', `synopsis_source` = NULL WHERE `title` = 'Avengers: Infinity War' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Marcello, mite toelettatore di cani in un litorale laziale decaduto, arrotonda spacciando cocaina e subisce la violenza parassitaria dell''ex pugile Simoncino, bullo del quartiere. La sua rivalsa, quando arriva, è tanto goffa quanto tremenda.', `synopsis_source` = NULL WHERE `title` = 'Dogman' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Miles Morales, adolescente di Brooklyn, viene morso da un ragno radioattivo mentre il collisore di Kingpin apre varchi tra dimensioni parallele. Affiancato da più versioni di Spider-Man — dal Peter Parker disilluso a Spider-Gwen — deve imparare a essere l''Uomo Ragno del proprio universo.', `synopsis_source` = NULL WHERE `title` = 'Spider-Man: Un nuovo universo' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Inghilterra, primo Settecento: alla corte della regina Anna, fragile e capricciosa, la favorita Lady Sarah governa di fatto il regno finché non arriva la cugina decaduta Abigail. La scalata di quest''ultima è una guerra di boudoir crudele e divertentissima.', `synopsis_source` = NULL WHERE `title` = 'La favorita' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il mondo è stato spopolato da creature cieche che cacciano qualsiasi suono; la famiglia Abbott sopravvive in una fattoria comunicando nella lingua dei segni. Un figlio in arrivo — e un parto è tutto tranne che silenzioso — mette il sistema alla prova.', `synopsis_source` = NULL WHERE `title` = 'A Quiet Place - Un posto tranquillo' AND `year` = 2018 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'La famiglia Kim, disoccupata e ingegnosa, si infiltra un membro alla volta al servizio dei ricchissimi Park: tutor, autista, governante. Il piano è perfetto finché il seminterrato della villa non rivela ciò che nasconde, e la commedia diventa altro.', `synopsis_source` = NULL WHERE `title` = 'Parasite' AND `year` = 2019 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Gotham, 1981: Arthur Fleck, clown a noleggio con una risata patologica e una madre fragile, viene respinto e umiliato da ogni istituzione della città. La sua discesa, tra tagli alla sanità pubblica e violenza crescente, ha un punto di arrivo con il trucco sul volto.', `synopsis_source` = NULL WHERE `title` = 'Joker' AND `year` = 2019 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Hollywood, 1969: l''attore televisivo in declino Rick Dalton e la sua controfigura e factotum Cliff Booth navigano un''industria che sta cambiando pelle, mentre accanto a loro si è trasferita Sharon Tate. Tarantino accarezza un''epoca e si prende la libertà di riscriverla.', `synopsis_source` = NULL WHERE `title` = 'C''era una volta a... Hollywood' AND `year` = 2019 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Fronte occidentale, aprile 1917: ai caporali Schofield e Blake viene ordinato di attraversare la terra di nessuno per consegnare entro l''alba un contrordine che fermerà un attacco destinato al massacro — tra i milleseicento uomini c''è il fratello di Blake. Il film corre con loro in un unico respiro.', `synopsis_source` = NULL WHERE `title` = '1917' AND `year` = 2019 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Dopo lo schiocco di Thanos, gli Avengers sopravvissuti vivono in un mondo dimezzato e senza scopo. Una possibilità assurda — una rapina nel tempo attraverso il regno quantico — li rimette insieme per l''ultima, gigantesca battaglia della saga.', `synopsis_source` = NULL WHERE `title` = 'Avengers: Endgame' AND `year` = 2019 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Charlie, regista teatrale newyorkese, e Nicole, attrice che vuole tornare a Los Angeles, si separano cercando di restare civili per il figlio. L''ingresso degli avvocati trasforma il dolore in guerra, senza mai perdere di vista l''affetto residuo.', `synopsis_source` = NULL WHERE `title` = 'Storia di un matrimonio' AND `year` = 2019 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il patriarca e giallista Harlan Thrombey viene trovato sgozzato dopo la festa dei suoi 85 anni, e l''eccentrico detective Benoit Blanc sospetta dell''intera famiglia di avvoltoi. Al centro c''è Marta, l''infermiera che non riesce a mentire senza vomitare.', `synopsis_source` = NULL WHERE `title` = 'Cena con delitto - Knives Out' AND `year` = 2019 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Germania, ultimi mesi della guerra: Jojo, dieci anni e un amico immaginario di nome Adolf, scopre che la madre nasconde in casa una ragazza ebrea. La propaganda che ha in testa si scontra con la persona che ha in soffitta.', `synopsis_source` = NULL WHERE `title` = 'Jojo Rabbit' AND `year` = 2019 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Tommaso Buscetta, boss dei due mondi, dopo lo sterminio della sua fazione decide di parlare con il giudice Falcone: è il primo grande pentito di mafia. Il maxiprocesso, il tradimento del codice e l''esilio raccontati da Bellocchio.', `synopsis_source` = NULL WHERE `title` = 'Il traditore' AND `year` = 2019 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un agente della CIA viene reclutato da un''organizzazione che maneggia oggetti a entropia invertita: proiettili che tornano indietro, persone che vivono a ritroso. La parola d''ordine è Tenet, la missione impedire una guerra che arriva dal futuro.', `synopsis_source` = NULL WHERE `title` = 'Tenet' AND `year` = 2020 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Fern, vedova sessantenne rimasta senza città quando la miniera chiude, carica la vita su un furgone e attraversa l''Ovest americano di lavoro stagionale in lavoro stagionale. Tra nomadi veri che interpretano se stessi, un''elegia sul perdere e ripartire.', `synopsis_source` = NULL WHERE `title` = 'Nomadland' AND `year` = 2020 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Anthony, ottantenne londinese, rifiuta ogni badante e giura che qualcuno gli ruba l''orologio; sua figlia Anne cerca di tenerlo al sicuro. Il film ci mette dentro la sua demenza: appartamenti che cambiano, volti che si scambiano, il tempo che non tiene.', `synopsis_source` = NULL WHERE `title` = 'The Father - Nulla è come sembra' AND `year` = 2020 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Joe Gardner, insegnante di musica con il sogno del jazz, muore il giorno dell''audizione della vita e si ritrova nell''Ante-Mondo, dove le anime nuove cercano la loro scintilla. In coppia con 22, anima che della Terra non vuole saperne, scopre cosa rende una vita degna di essere vissuta.', `synopsis_source` = NULL WHERE `title` = 'Soul' AND `year` = 2020 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Quattro insegnanti di liceo danesi, spenti e in crisi, testano una teoria: mantenere costante mezzo grammo di alcol nel sangue rende migliori. All''inizio funziona — lezioni brillanti, matrimoni rianimati — poi l''esperimento chiede il conto.', `synopsis_source` = NULL WHERE `title` = 'Un altro giro' AND `year` = 2020 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'La vita di Antonio Ligabue, respinto dalla Svizzera e cresciuto ai margini della Bassa reggiana tra fame, internamenti e derisione. La pittura — tigri, leopardi, autoritratti feroci — è la sua rivincita su un mondo che lo voleva invisibile.', `synopsis_source` = NULL WHERE `title` = 'Volevo nascondermi' AND `year` = 2020 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il duca Leto Atreides accetta il feudo di Arrakis, il pianeta desertico da cui viene la spezia che regge l''impero, sapendo che è una trappola degli Harkonnen. Suo figlio Paul, tormentato da visioni, troverà il proprio destino tra i Fremen del deserto.', `synopsis_source` = NULL WHERE `title` = 'Dune' AND `year` = 2021 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Napoli, anni Ottanta: Fabietto cresce tra un clan familiare chiassoso e tenerissimo e il miraggio di Maradona in maglia azzurra. Un lutto improvviso spacca in due la sua adolescenza, e il cinema diventa la via per non morire di realtà.', `synopsis_source` = NULL WHERE `title` = 'È stata la mano di Dio' AND `year` = 2021 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Montana, 1925: il rancher Phil Burbank, carismatico e crudele, tormenta la nuova moglie del fratello e suo figlio Peter, ragazzo esile che fabbrica fiori di carta. I rapporti di forza nel ranch sono più mobili di quanto Phil creda.', `synopsis_source` = NULL WHERE `title` = 'Il potere del cane' AND `year` = 2021 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Due anni dopo la morte della moglie attrice, il regista teatrale Kafuku accetta una residenza a Hiroshima, dove gli assegnano una giovane autista taciturna, Misaki. Tra le prove di Zio Vanja e i viaggi sulla Saab rossa, i due si raccontano i rispettivi lutti.', `synopsis_source` = NULL WHERE `title` = 'Drive My Car' AND `year` = 2021 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'L''identità di Spider-Man è stata svelata al mondo e Peter Parker chiede a Doctor Strange un incantesimo per farla dimenticare. L''incantesimo si rompe e dai multiversi arrivano i nemici — e gli alleati — di altri Uomini Ragno.', `synopsis_source` = NULL WHERE `title` = 'Spider-Man: No Way Home' AND `year` = 2021 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Julie, trentenne di Oslo, cambia facoltà, lavori e uomini cercando di capire chi è, tra un fumettista più grande che la ama e un barista che la fa sentire viva. Dodici capitoli, un prologo e un epilogo sulla libertà e i suoi costi.', `synopsis_source` = NULL WHERE `title` = 'La persona peggiore del mondo' AND `year` = 2021 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Roma occupata dai nazisti: quattro fenomeni da baraccone — l''uomo calamita, la donna barbuta elettrica, il nano forzuto e il ragazzo lupo — perdono il loro circo e il loro protettore. Tra rastrellamenti e un pianista tedesco che vede il futuro, i freak diventano partigiani.', `synopsis_source` = NULL WHERE `title` = 'Freaks Out' AND `year` = 2021 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Evelyn Wang, lavanderia self-service e verifica fiscale alle porte, scopre di essere la variante più fallita di se stessa in un multiverso infinito — e proprio per questo l''unica che può salvarlo. Tra salti assurdi e dita a würstel, il vero campo di battaglia è la sua famiglia.', `synopsis_source` = NULL WHERE `title` = 'Everything Everywhere All at Once' AND `year` = 2022 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Pete ''Maverick'' Mitchell, dopo trent''anni ancora capitano per vocazione all''insubordinazione, viene richiamato a Top Gun per addestrare i migliori giovani piloti a una missione quasi suicida. Tra loro c''è Rooster, il figlio del suo amico Goose.', `synopsis_source` = NULL WHERE `title` = 'Top Gun: Maverick' AND `year` = 2022 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Su un''isoletta irlandese, nel 1923, Colm smette da un giorno all''altro di rivolgere la parola all''amico di sempre Pádraic: dice che gli fa perdere tempo. Il rifiuto degenera in un ultimatum grottesco e sanguinoso, mentre sulla terraferma la guerra civile brontola.', `synopsis_source` = NULL WHERE `title` = 'Gli spiriti dell''isola' AND `year` = 2022 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Pandora, più di dieci anni dopo: Jake Sully e Neytiri, ormai genitori, devono lasciare la foresta quando gli umani tornano in forze, e chiedono asilo al popolo della barriera corallina Metkayina. I figli imparano la via dell''acqua mentre la guerra li raggiunge.', `synopsis_source` = NULL WHERE `title` = 'Avatar - La via dell''acqua' AND `year` = 2022 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Paul Bäumer e i compagni di scuola si arruolano nel 1917 gonfi di retorica patriottica e vengono maciullati dalla realtà delle trincee. Mentre i generali trattano l''armistizio, al fronte si continua a morire fino all''ultimo minuto.', `synopsis_source` = NULL WHERE `title` = 'Niente di nuovo sul fronte occidentale' AND `year` = 2022 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Pietro, ragazzino di città, e Bruno, montanaro coetaneo, si incontrano da bambini in un paese quasi disabitato delle Alpi e si legano per la vita. Il padre di Pietro, la montagna e un rudere da ricostruire misurano la loro amicizia lungo i decenni.', `synopsis_source` = NULL WHERE `title` = 'Le otto montagne' AND `year` = 2022 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un influencer e la sua fidanzata modella vengono invitati su uno yacht di lusso con un equipaggio ossequioso, un capitano marxista ubriaco e un parterre di ricchi grotteschi. Tempesta, naufragio e isola deserta rimescolano la piramide sociale.', `synopsis_source` = NULL WHERE `title` = 'Triangle of Sadness' AND `year` = 2022 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Secondo anno di Batman a Gotham: un serial killer che si firma l''Enigmista elimina i notabili della città lasciando indovinelli indirizzati proprio a lui. L''indagine scava nella corruzione e nella storia dei Wayne, tra una Selina Kyle in cerca di vendetta e una pioggia che non smette mai.', `synopsis_source` = NULL WHERE `title` = 'The Batman' AND `year` = 2022 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il fisico J. Robert Oppenheimer guida a Los Alamos il progetto Manhattan fino al lampo di Trinity, poi passa il resto della vita a fare i conti con ciò che ha scatenato. Nolan intreccia l''ascesa, il processo di sicurezza del 1954 e la resa dei conti con Strauss.', `synopsis_source` = NULL WHERE `title` = 'Oppenheimer' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Barbie Stereotipo vive una giornata perfetta dopo l''altra a Barbieland, finché pensieri di morte e piedi piatti non la costringono a viaggiare nel mondo reale con un Ken in cerca di scopo. La scoperta del patriarcato scombina entrambi i mondi.', `synopsis_source` = NULL WHERE `title` = 'Barbie' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Bella Baxter, riportata in vita dallo scienziato Godwin Baxter con un cervello nuovo, divora il mondo senza vergogna né buone maniere: sesso, filosofia, socialismo. La sua educazione sentimentale attraverso un''Europa steampunk è una liberazione in technicolor.', `synopsis_source` = NULL WHERE `title` = 'Povere creature!' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Oklahoma, anni Venti: la nazione Osage è la più ricca al mondo per il petrolio, e i suoi membri muoiono uno dopo l''altro. Ernest Burkhart, tornato dalla guerra, sposa l''osage Mollie mentre lo zio ''King'' Hale orchestra il sistematico saccheggio — matrimoni compresi.', `synopsis_source` = NULL WHERE `title` = 'Killers of the Flower Moon' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Il marito di Sandra precipita dal balcone dello chalet e l''unico testimone è il figlio ipovedente Daniel. Il processo seziona il matrimonio della coppia — carriere, lingue, tradimenti, una registrazione — finché la verità diventa questione di scelta.', `synopsis_source` = NULL WHERE `title` = 'Anatomia di una caduta' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'La famiglia del comandante di Auschwitz Rudolf Höss vive in una villa idilliaca con piscina e giardino, separata dal campo solo da un muro. Il film non varca mai il muro: l''orrore è tutto nel suono, e nella normalità di chi non lo sente più.', `synopsis_source` = NULL WHERE `title` = 'La zona d''interesse' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Nora e Hae Sung, compagni di scuola a Seul, si perdono quando la famiglia di lei emigra; si ritrovano online a vent''anni e di persona a quaranta, a New York, dove Nora è sposata. Tre giorni per chiedersi cosa sono stati e cosa non saranno: in-yun, dicono i coreani.', `synopsis_source` = NULL WHERE `title` = 'Past Lives' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Roma, 1946: Delia fa la moglie e la madre sotto un marito padrone, tra lavori pagati meno degli uomini e una figlia da maritare. Una lettera misteriosa le accende un''idea di riscatto che culmina nel giorno in cui le donne italiane votano per la prima volta.', `synopsis_source` = NULL WHERE `title` = 'C''è ancora domani' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Seydou e Moussa, cugini sedicenni di Dakar, partono di nascosto per raggiungere l''Europa con i risparmi di piccoli lavori. Il viaggio vero — Sahara, prigioni libiche, un barcone da guidare — è l''odissea che i telegiornali non raccontano.', `synopsis_source` = NULL WHERE `title` = 'Io capitano' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Natale 1970: nel collegio deserto restano il professore di lettere classiche più odiato del campus, una cuoca che ha appena perso il figlio in Vietnam e uno studente piantato lì dalla madre. Due settimane di neve, whisky e ferite che si annusano a vicenda.', `synopsis_source` = NULL WHERE `title` = 'The Holdovers - Lezioni di vita' AND `year` = 2023 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Paul Atreides, accolto dai Fremen dopo il massacro della sua casata, impara la via del deserto, cavalca il verme e ama Chani, mentre la profezia costruita attorno a lui diventa arma. La vendetta contro Harkonnen e Imperatore ha un prezzo: la guerra santa.', `synopsis_source` = NULL WHERE `title` = 'Dune - Parte due' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'L''architetto ungherese László Tóth, sopravvissuto ai campi, sbarca in America nel 1947 e ricomincia da zero, finché il magnate Harrison Van Buren non gli commissiona l''opera di una vita. Trent''anni di genio, dipendenza e potere: il sogno americano in formato monumentale.', `synopsis_source` = NULL WHERE `title` = 'The Brutalist' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Ani, spogliarellista di Brooklyn, sposa d''impulso il figlio viziato di un oligarca russo dopo una settimana di eccessi. Quando la famiglia di lui manda gli scagnozzi ad annullare il matrimonio, la favola di Cenerentola diventa una farsa amara e velocissima.', `synopsis_source` = NULL WHERE `title` = 'Anora' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Alla morte del papa, il cardinale Lawrence deve gestire il conclave: fazioni progressiste e reazionarie, ambizioni traboccanti e un cardinale segreto nominato in pectore. Ogni scrutinio porta una rivelazione, fino a quella finale.', `synopsis_source` = NULL WHERE `title` = 'Conclave' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Elisabeth Sparkle, star del fitness televisivo rottamata a cinquant''anni, si inietta una sostanza clandestina che genera una versione di sé giovane e perfetta, Sue. Le regole sono semplici — sette giorni a testa, senza sgarri — e vengono infrante subito, con conseguenze sempre più mostruose.', `synopsis_source` = NULL WHERE `title` = 'The Substance' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Tashi, ex promessa del tennis diventata allenatrice-moglie del campione Art, iscrive il marito in crisi a un torneo minore dove trovano Patrick, ex migliore amico di lui ed ex fidanzato di lei. Tredici anni di triangolo raccontati match point dopo match point.', `synopsis_source` = NULL WHERE `title` = 'Challengers' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'New York, 1961: il diciannovenne Bob Dylan arriva dal Minnesota con una chitarra e la faccia tosta di presentarsi a Woody Guthrie in ospedale. La scalata del Greenwich Village fino allo scandalo elettrico di Newport 1965, con Joan Baez e Pete Seeger a fare da coro.', `synopsis_source` = NULL WHERE `title` = 'A Complete Unknown' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = '1944, alta valle trentina: la guerra è un''eco lontana finché in paese non arriva un soldato siciliano disertore, che sposa Lucia, la figlia del maestro. Le stagioni della montagna scandiscono nascite, partenze e un dopoguerra che non riporta indietro nessuno.', `synopsis_source` = NULL WHERE `title` = 'Vermiglio' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Partenope nasce nel mare di Posillipo nel 1950 e attraversa i decenni bellissima e insondabile, tra un amore impossibile, l''antropologia e una Napoli che è madre e specchio. Sorrentino la segue come si segue una città: senza mai possederla.', `synopsis_source` = NULL WHERE `title` = 'Parthenope' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Un''alluvione sommerge il mondo e un gatto nero solitario trova rifugio su una barca a vela insieme a un capibara, un lemure, un cane e un uccello segretario. Senza una parola di dialogo, la piccola arca impara la convivenza.', `synopsis_source` = NULL WHERE `title` = 'Flow - Un mondo da salvare' AND `year` = 2024 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Delta del Mississippi, 1932: i gemelli Smoke e Stack tornano da Chicago per aprire un juke joint per la comunità nera, con il cugino Sammie e la sua chitarra benedetta e maledetta. La prima notte del locale attira avventori che di umano non hanno niente.', `synopsis_source` = NULL WHERE `title` = 'I peccatori' AND `year` = 2025 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Sonny Hayes, ex promessa della Formula 1 che vive di corse minori e roulotte, viene richiamato dal vecchio amico Ruben per salvare la sua scuderia sull''orlo del fallimento. Accanto al rookie Joshua Pearce, l''ultimo giro di giostra del veterano.', `synopsis_source` = NULL WHERE `title` = 'F1 - Il film' AND `year` = 2025 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'L''ex rivoluzionario Bob Ferguson, sedici anni dopo i giorni delle azioni armate, vive paranoico e fumato crescendo da solo la figlia Willa. Quando il colonnello Lockjaw, fantasma del suo passato, la fa cercare, Bob deve ricordarsi chi era.', `synopsis_source` = NULL WHERE `title` = 'Una battaglia dopo l''altra' AND `year` = 2025 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Victor Frankenstein, chirurgo geniale divorato dall''ambizione, assembla e anima una creatura che poi rifiuta con orrore. Del Toro racconta entrambe le versioni — quella del padre e quella del figlio — in un gotico sontuoso sul mostro che il mostro non è.', `synopsis_source` = NULL WHERE `title` = 'Frankenstein' AND `year` = 2025 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Jake Sully e Neytiri, ancora feriti dalla perdita subita tra i Metkayina, affrontano un nuovo nemico Na''vi: il popolo della cenere di Varang, alleato degli umani ritornati. La guerra per Pandora tocca il fuoco dopo l''acqua.', `synopsis_source` = NULL WHERE `title` = 'Avatar - Fuoco e cenere' AND `year` = 2025 AND `synopsis` IS NULL;--> statement-breakpoint
UPDATE `movies` SET `synopsis` = 'Stratford, fine Cinquecento: Agnes, guaritrice che sente il bosco, sposa un giovane precettore di latino destinato al teatro di Londra. La morte del figlio Hamnet, undici anni, spacca il matrimonio in due lutti diversi — finché un dramma dal nome quasi uguale non li ricuce.', `synopsis_source` = NULL WHERE `title` = 'Hamnet' AND `year` = 2025 AND `synopsis` IS NULL;
