// Generato da scripts/build-generated-directors-manifest.mjs. Non modificare a mano.
const GENERATED_DIRECTOR_PORTRAITS: Record<string, string> = {
  "Akira Kurosawa": "/directors/generated/akira-kurosawa.webp",
  "Alejandro González Iñárritu": "/directors/generated/alejandro-gonzalez-inarritu.webp",
  "Alex Garland": "/directors/generated/alex-garland.webp",
  "Alexander Payne": "/directors/generated/alexander-payne.webp",
  "Alfonso Cuarón": "/directors/generated/alfonso-cuaron.webp",
  "Alfred Hitchcock": "/directors/generated/alfred-hitchcock.webp",
  "Andrej Tarkovskij": "/directors/generated/andrej-tarkovskij.webp",
  "Andrew Adamson": "/directors/generated/andrew-adamson.webp",
  "Andrew Stanton": "/directors/generated/andrew-stanton.webp",
  "Andy Muschietti": "/directors/generated/andy-muschietti.webp",
  "Ang Lee": "/directors/generated/ang-lee.webp",
  "Anthony e Joe Russo": "/directors/generated/anthony-e-joe-russo.webp",
  "Ari Aster": "/directors/generated/ari-aster.webp",
  "Asghar Farhadi": "/directors/generated/asghar-farhadi.webp",
  "Barry Jenkins": "/directors/generated/barry-jenkins.webp",
  "Barry Sonnenfeld": "/directors/generated/barry-sonnenfeld.webp",
  "Ben Affleck": "/directors/generated/ben-affleck.webp",
  "Billy Wilder": "/directors/generated/billy-wilder.webp",
  "Bob Persichetti": "/directors/generated/bob-persichetti.webp",
  "Bong Joon-ho": "/directors/generated/bong-joon-ho.webp",
  "Brad Bird": "/directors/generated/brad-bird.webp",
  "Bradley Cooper": "/directors/generated/bradley-cooper.webp",
  "Brady Corbet": "/directors/generated/brady-corbet.webp",
  "Brian De Palma": "/directors/generated/brian-de-palma.webp",
  "Bryan Singer": "/directors/generated/bryan-singer.webp",
  "Carol Reed": "/directors/generated/carol-reed.webp",
  "Celine Song": "/directors/generated/celine-song.webp",
  "Chad Stahelski": "/directors/generated/chad-stahelski.webp",
  "Charlie Chaplin": "/directors/generated/charlie-chaplin.webp",
  "Charlotte Vandermeersch": "/directors/generated/charlotte-vandermeersch.webp",
  "Chloé Zhao": "/directors/generated/chloe-zhao.webp",
  "Chris Columbus": "/directors/generated/chris-columbus.webp",
  "Christopher Nolan": "/directors/generated/christopher-nolan.webp",
  "Clint Eastwood": "/directors/generated/clint-eastwood.webp",
  "Coralie Fargeat": "/directors/generated/coralie-fargeat.webp",
  "Curtis Hanson": "/directors/generated/curtis-hanson.webp",
  "Damien Chazelle": "/directors/generated/damien-chazelle.webp",
  "Daniel Kwan": "/directors/generated/daniel-kwan.webp",
  "Daniel Scheinert": "/directors/generated/daniel-scheinert.webp",
  "Danny Boyle": "/directors/generated/danny-boyle.webp",
  "Dario Argento": "/directors/generated/dario-argento.webp",
  "Darren Aronofsky": "/directors/generated/darren-aronofsky.webp",
  "David Fincher": "/directors/generated/david-fincher.webp",
  "David Frankel": "/directors/generated/david-frankel.webp",
  "David Hand": "/directors/generated/david-hand.webp",
  "David Lean": "/directors/generated/david-lean.webp",
  "David Lynch": "/directors/generated/david-lynch.webp",
  "Denis Villeneuve": "/directors/generated/denis-villeneuve.webp",
  "Edward Berger": "/directors/generated/edward-berger.webp",
  "Elia Kazan": "/directors/generated/elia-kazan.webp",
  "Éric Toledano": "/directors/generated/eric-toledano.webp",
  "Ernest B. Schoedsack": "/directors/generated/ernest-b-schoedsack.webp",
  "F. W. Murnau": "/directors/generated/f-w-murnau.webp",
  "Fausto Brizzi": "/directors/generated/fausto-brizzi.webp",
  "Federico Fellini": "/directors/generated/federico-fellini.webp",
  "Felix van Groeningen": "/directors/generated/felix-van-groeningen.webp",
  "Fernando Meirelles": "/directors/generated/fernando-meirelles.webp",
  "Florian Henckel von Donnersmarck": "/directors/generated/florian-henckel-von-donnersmarck.webp",
  "Florian Zeller": "/directors/generated/florian-zeller.webp",
  "Francis Ford Coppola": "/directors/generated/francis-ford-coppola.webp",
  "François Truffaut": "/directors/generated/francois-truffaut.webp",
  "Frank Capra": "/directors/generated/frank-capra.webp",
  "Frank Darabont": "/directors/generated/frank-darabont.webp",
  "Franklin J. Schaffner": "/directors/generated/franklin-j-schaffner.webp",
  "Fritz Lang": "/directors/generated/fritz-lang.webp",
  "Gabriele Lavia": "/directors/generated/gabriele-lavia.webp",
  "Gabriele Mainetti": "/directors/generated/gabriele-mainetti.webp",
  "Gene Kelly": "/directors/generated/gene-kelly.webp",
  "Gennaro Nunziante": "/directors/generated/gennaro-nunziante.webp",
  "George A. Romero": "/directors/generated/george-a-romero.webp",
  "George Lucas": "/directors/generated/george-lucas.webp",
  "George Miller": "/directors/generated/george-miller.webp",
  "Gillo Pontecorvo": "/directors/generated/gillo-pontecorvo.webp",
  "Gints Zilbalodis": "/directors/generated/gints-zilbalodis.webp",
  "Giorgio Diritti": "/directors/generated/giorgio-diritti.webp",
  "Giuseppe Tornatore": "/directors/generated/giuseppe-tornatore.webp",
  "Greta Gerwig": "/directors/generated/greta-gerwig.webp",
  "Guillermo del Toro": "/directors/generated/guillermo-del-toro.webp",
  "Guy Ritchie": "/directors/generated/guy-ritchie.webp",
  "Hayao Miyazaki": "/directors/generated/hayao-miyazaki.webp",
  "Ingmar Bergman": "/directors/generated/ingmar-bergman.webp",
  "Ivan Reitman": "/directors/generated/ivan-reitman.webp",
  "J.J. Abrams": "/directors/generated/j-j-abrams.webp",
  "Jacques Audiard": "/directors/generated/jacques-audiard.webp",
  "James Cameron": "/directors/generated/james-cameron.webp",
  "James Mangold": "/directors/generated/james-mangold.webp",
  "James McTeigue": "/directors/generated/james-mcteigue.webp",
  "Jane Campion": "/directors/generated/jane-campion.webp",
  "Jason Reitman": "/directors/generated/jason-reitman.webp",
  "Jean Renoir": "/directors/generated/jean-renoir.webp",
  "Jean-Luc Godard": "/directors/generated/jean-luc-godard.webp",
  "Jean-Pierre Jeunet": "/directors/generated/jean-pierre-jeunet.webp",
  "Jerome Robbins": "/directors/generated/jerome-robbins.webp",
  "Joachim Trier": "/directors/generated/joachim-trier.webp",
  "Joel Coen": "/directors/generated/joel-coen.webp",
  "Joel e Ethan Coen": "/directors/generated/joel-e-ethan-coen.webp",
  "John Carpenter": "/directors/generated/john-carpenter.webp",
  "John G. Avildsen": "/directors/generated/john-g-avildsen.webp",
  "John Krasinski": "/directors/generated/john-krasinski.webp",
  "John Landis": "/directors/generated/john-landis.webp",
  "John Lasseter": "/directors/generated/john-lasseter.webp",
  "John McTiernan": "/directors/generated/john-mctiernan.webp",
  "Jon Watts": "/directors/generated/jon-watts.webp",
  "Jonathan Dayton": "/directors/generated/jonathan-dayton.webp",
  "Jonathan Demme": "/directors/generated/jonathan-demme.webp",
  "Jonathan Glazer": "/directors/generated/jonathan-glazer.webp",
  "Jordan Peele": "/directors/generated/jordan-peele.webp",
  "Joseph Kosinski": "/directors/generated/joseph-kosinski.webp",
  "Joss Whedon": "/directors/generated/joss-whedon.webp",
  "Justine Triet": "/directors/generated/justine-triet.webp",
  "Kane Parsons": "/directors/generated/kane-parsons.webp",
  "Kenneth Lonergan": "/directors/generated/kenneth-lonergan.webp",
  "Lana e Lilly Wachowski": "/directors/generated/lana-e-lilly-wachowski.webp",
  "Larry Charles": "/directors/generated/larry-charles.webp",
  "Lee Unkrich": "/directors/generated/lee-unkrich.webp",
  "Luc Besson": "/directors/generated/luc-besson.webp",
  "Luca Guadagnino": "/directors/generated/luca-guadagnino.webp",
  "Luca Miniero": "/directors/generated/luca-miniero.webp",
  "Luchino Visconti": "/directors/generated/luchino-visconti.webp",
  "Luciano Salce": "/directors/generated/luciano-salce.webp",
  "M. Night Shyamalan": "/directors/generated/m-night-shyamalan.webp",
  "Makoto Shinkai": "/directors/generated/makoto-shinkai.webp",
  "Marco Bellocchio": "/directors/generated/marco-bellocchio.webp",
  "Marco Tullio Giordana": "/directors/generated/marco-tullio-giordana.webp",
  "Martin Campbell": "/directors/generated/martin-campbell.webp",
  "Martin McDonagh": "/directors/generated/martin-mcdonagh.webp",
  "Martin Scorsese": "/directors/generated/martin-scorsese.webp",
  "Matt Reeves": "/directors/generated/matt-reeves.webp",
  "Matt Ross": "/directors/generated/matt-ross.webp",
  "Matteo Garrone": "/directors/generated/matteo-garrone.webp",
  "Maura Delpero": "/directors/generated/maura-delpero.webp",
  "Mel Gibson": "/directors/generated/mel-gibson.webp",
  "Merian C. Cooper": "/directors/generated/merian-c-cooper.webp",
  "Michael Cimino": "/directors/generated/michael-cimino.webp",
  "Michael Curtiz": "/directors/generated/michael-curtiz.webp",
  "Michael Haneke": "/directors/generated/michael-haneke.webp",
  "Michael Mann": "/directors/generated/michael-mann.webp",
  "Michel Gondry": "/directors/generated/michel-gondry.webp",
  "Michel Hazanavicius": "/directors/generated/michel-hazanavicius.webp",
  "Michelangelo Antonioni": "/directors/generated/michelangelo-antonioni.webp",
  "Mike Nichols": "/directors/generated/mike-nichols.webp",
  "Miloš Forman": "/directors/generated/milos-forman.webp",
  "Nanni Moretti": "/directors/generated/nanni-moretti.webp",
  "Neill Blomkamp": "/directors/generated/neill-blomkamp.webp",
  "Nicholas Ray": "/directors/generated/nicholas-ray.webp",
  "Nicolas Winding Refn": "/directors/generated/nicolas-winding-refn.webp",
  "Noah Baumbach": "/directors/generated/noah-baumbach.webp",
  "Olivier Nakache": "/directors/generated/olivier-nakache.webp",
  "Orson Welles": "/directors/generated/orson-welles.webp",
  "Paola Cortellesi": "/directors/generated/paola-cortellesi.webp",
  "Paolo Genovese": "/directors/generated/paolo-genovese.webp",
  "Paolo Sorrentino": "/directors/generated/paolo-sorrentino.webp",
  "Park Chan-wook": "/directors/generated/park-chan-wook.webp",
  "Paul Thomas Anderson": "/directors/generated/paul-thomas-anderson.webp",
  "Pete Docter": "/directors/generated/pete-docter.webp",
  "Peter Cattaneo": "/directors/generated/peter-cattaneo.webp",
  "Peter Farrelly": "/directors/generated/peter-farrelly.webp",
  "Peter Jackson": "/directors/generated/peter-jackson.webp",
  "Peter Ramsey": "/directors/generated/peter-ramsey.webp",
  "Peter Weir": "/directors/generated/peter-weir.webp",
  "Quentin Dupieux": "/directors/generated/quentin-dupieux.webp",
  "Quentin Tarantino": "/directors/generated/quentin-tarantino.webp",
  "Rian Johnson": "/directors/generated/rian-johnson.webp",
  "Richard Kelly": "/directors/generated/richard-kelly.webp",
  "Richard Linklater": "/directors/generated/richard-linklater.webp",
  "Ridley Scott": "/directors/generated/ridley-scott.webp",
  "Robert Eggers": "/directors/generated/robert-eggers.webp",
  "Robert Stevenson": "/directors/generated/robert-stevenson.webp",
  "Robert Wise": "/directors/generated/robert-wise.webp",
  "Robert Zemeckis": "/directors/generated/robert-zemeckis.webp",
  "Roberto Benigni": "/directors/generated/roberto-benigni.webp",
  "Roberto Rossellini": "/directors/generated/roberto-rossellini.webp",
  "Rodney Rothman": "/directors/generated/rodney-rothman.webp",
  "Roland Emmerich": "/directors/generated/roland-emmerich.webp",
  "Roman Polanski": "/directors/generated/roman-polanski.webp",
  "Ron Howard": "/directors/generated/ron-howard.webp",
  "Ruben Östlund": "/directors/generated/ruben-ostlund.webp",
  "Ryan Coogler": "/directors/generated/ryan-coogler.webp",
  "Ryusuke Hamaguchi": "/directors/generated/ryusuke-hamaguchi.webp",
  "Sam Mendes": "/directors/generated/sam-mendes.webp",
  "Sean Baker": "/directors/generated/sean-baker.webp",
  "Sean Penn": "/directors/generated/sean-penn.webp",
  "Sergej Ėjzenštejn": "/directors/generated/sergej-ejzenstejn.webp",
  "Sergio Leone": "/directors/generated/sergio-leone.webp",
  "Sidney Lumet": "/directors/generated/sidney-lumet.webp",
  "Sofia Coppola": "/directors/generated/sofia-coppola.webp",
  "Spike Jonze": "/directors/generated/spike-jonze.webp",
  "Stanley Donen": "/directors/generated/stanley-donen.webp",
  "Stanley Kubrick": "/directors/generated/stanley-kubrick.webp",
  "Steve McQueen": "/directors/generated/steve-mcqueen.webp",
  "Steven Spielberg": "/directors/generated/steven-spielberg.webp",
  "Sydney Sibilia": "/directors/generated/sydney-sibilia.webp",
  "Taika Waititi": "/directors/generated/taika-waititi.webp",
  "Thomas Vinterberg": "/directors/generated/thomas-vinterberg.webp",
  "Tim Burton": "/directors/generated/tim-burton.webp",
  "Todd Phillips": "/directors/generated/todd-phillips.webp",
  "Tom Hooper": "/directors/generated/tom-hooper.webp",
  "Tom McCarthy": "/directors/generated/tom-mccarthy.webp",
  "Valerie Faris": "/directors/generated/valerie-faris.webp",
  "Vicky Jenson": "/directors/generated/vicky-jenson.webp",
  "Victor Fleming": "/directors/generated/victor-fleming.webp",
  "Vittorio De Sica": "/directors/generated/vittorio-de-sica.webp",
  "Wes Anderson": "/directors/generated/wes-anderson.webp",
  "William Friedkin": "/directors/generated/william-friedkin.webp",
  "William Wyler": "/directors/generated/william-wyler.webp",
  "Woody Allen": "/directors/generated/woody-allen.webp",
  "Yorgos Lanthimos": "/directors/generated/yorgos-lanthimos.webp",
  "Zach Cregger": "/directors/generated/zach-cregger.webp",
};

export function generatedDirectorPortraitFor(name: string): string | null {
  return GENERATED_DIRECTOR_PORTRAITS[name] ?? null;
}
