// Cento classici 1921–1994: metadati, durata, sinossi originale e cue visivi.
// I cue guidano artwork riconoscibili senza copiare locandine, frame o volti degli attori.
const film = (title, year, director, actors, genres, runtime, synopsis, cues) => ({
  title,
  year,
  director,
  actors,
  genres,
  runtime,
  synopsis,
  cues,
});

export const CLASSIC_FILMS = [
  film("Il monello", 1921, "Charlie Chaplin", "Charlie Chaplin, Jackie Coogan, Edna Purviance", "Commedia, Drammatico", 68,
    "Un vagabondo trova un neonato abbandonato e finisce per crescerlo come un figlio. Cinque anni dopo, il loro ingegnoso sodalizio di strada viene minacciato dalle autorità e dal ritorno della madre.",
    "a generic bowler-hatted tramp silhouette and small boy, broken-window repair scheme, abandoned baby carriage, rooftop chase above a poor city district"),
  film("Nosferatu", 1922, "F. W. Murnau", "Max Schreck, Gustav von Wangenheim, Greta Schröder", "Horror", 94,
    "Un giovane agente immobiliare raggiunge il castello del conte Orlok per concludere una vendita, ignorando di aver aperto la strada a un vampiro. Una nave fantasma porta il conte e la peste nella città della sua promessa sposa.",
    "expressionist castle, elongated vampire shadow climbing stairs, plague ship entering harbor, rats and coffin silhouettes, no exact character face"),
  film("La corazzata Potëmkin", 1925, "Sergej Ėjzenštejn", "Aleksandr Antonov, Vladimir Barskij, Grigorij Aleksandrov", "Storico, Drammatico", 75,
    "Nel 1905 i marinai della Potëmkin si ribellano agli ufficiali dopo l'ennesima umiliazione. La rivolta trova solidarietà a Odessa, dove la repressione trasforma una protesta in simbolo rivoluzionario.",
    "Odessa Steps crowded in panic, runaway baby carriage, mutinous sailors beneath naval flag without symbols, massive battleship guns in harbor"),
  film("Metropolis", 1927, "Fritz Lang", "Brigitte Helm, Gustav Fröhlich, Alfred Abel", "Fantascienza, Drammatico", 153,
    "Nella città del futuro i privilegiati vivono tra grattacieli e giardini, mentre gli operai alimentano macchine sotterranee. Il figlio del padrone scopre quel mondo e una donna-robot incendia il conflitto sociale.",
    "towering art-deco city, golden female robot silhouette, workers marching into giant clock-machine, underground engine hall, stark expressionist geometry"),
  film("Luci della città", 1931, "Charlie Chaplin", "Charlie Chaplin, Virginia Cherrill, Harry Myers", "Commedia, Romantico", 87,
    "Un vagabondo si innamora di una fioraia cieca, che lo crede ricco, e cerca in ogni modo il denaro per curarla. Un milionario amico solo quando è ubriaco complica ogni suo generoso tentativo.",
    "blind flower seller stall, generic bowler-hatted tramp silhouette, millionaire limousine, boxing ring and single white flower, silent-era city night"),
  film("M - Il mostro di Düsseldorf", 1931, "Fritz Lang", "Peter Lorre, Otto Wernicke, Gustaf Gründgens", "Thriller, Crime", 111,
    "Una città terrorizzata cerca l'assassino di bambine mentre la polizia stringe il cerchio e la malavita, esasperata dai controlli, organizza una caccia parallela. Il sospetto diventa preda di un intero sottobosco urbano.",
    "chalk letter M marked on coat back, child balloon caught in telephone wires, looming shadow over blank wanted poster, police and underworld searchlights crossing wet city"),
  film("King Kong", 1933, "Merian C. Cooper, Ernest B. Schoedsack", "Fay Wray, Robert Armstrong, Bruce Cabot", "Avventura, Fantasy", 100,
    "Una troupe raggiunge un'isola sconosciuta per girare un film e incontra una civiltà che venera un gorilla gigantesco. Catturato e portato a New York, Kong trasforma lo spettacolo in tragedia.",
    "giant ape silhouette atop Empire State Building, circling biplanes, jungle gate and chains, tiny blonde figure in hand, no exact actor likeness"),
  film("Tempi moderni", 1936, "Charlie Chaplin", "Charlie Chaplin, Paulette Goddard, Henry Bergman", "Commedia, Drammatico", 87,
    "Un operaio schiacciato dai ritmi della catena di montaggio perde il lavoro e attraversa scioperi, prigione e precarietà. Con una giovane senza casa prova a costruire una felicità fuori dagli ingranaggi.",
    "generic little-worker silhouette trapped inside giant gears, assembly line and wrenches, factory clock, roadside walk with young companion at dawn"),
  film("Biancaneve e i sette nani", 1937, "David Hand", "Adriana Caselotti, Lucille La Verne, Harry Stockwell (voci)", "Animazione, Fantasy", 83,
    "Una principessa perseguitata dalla matrigna trova rifugio nella casa di sette minatori. La regina, ossessionata dalla propria bellezza, prepara una mela avvelenata per riprendersi il primato.",
    "original fairy-tale princess silhouette, red poisoned apple, seven mining lanterns outside forest cottage, magic mirror and raven, no Disney character design"),
  film("La grande illusione", 1937, "Jean Renoir", "Jean Gabin, Dita Parlo, Erich von Stroheim", "Guerra, Drammatico", 114,
    "Durante la Prima guerra mondiale, ufficiali francesi di classi diverse tentano la fuga da campi di prigionia tedeschi. Tra carcerieri e prigionieri emergono solidarietà destinate a scomparire con il vecchio mondo.",
    "World War I prison castle, French and German officer silhouettes sharing table, tunnel tools beneath theatrical costumes, two escapees crossing snowy mountain border"),
  film("Il mago di Oz", 1939, "Victor Fleming", "Judy Garland, Frank Morgan, Ray Bolger", "Fantasy, Musical", 102,
    "Un tornado trascina Dorothy e il suo cane dal Kansas nel regno di Oz. Seguendo una strada gialla verso la Città di Smeraldo, incontra tre compagni convinti di non avere ciò che già possiedono.",
    "yellow brick road to emerald city, tornado carrying Kansas farmhouse, four anonymous traveler silhouettes with small dog, poppy field, original designs"),
  film("Via col vento", 1939, "Victor Fleming", "Vivien Leigh, Clark Gable, Olivia de Havilland", "Storico, Romantico", 238,
    "Scarlett O'Hara attraversa la guerra civile americana aggrappandosi alla piantagione di Tara e a un amore idealizzato. Rhett Butler riconosce la sua forza, ma non può salvarla da ogni perdita.",
    "burning Atlanta skyline, plantation staircase and ruined cotton field, green curtain fabric on sewing table, two distant lovers against red sunset"),
  film("Il grande dittatore", 1940, "Charlie Chaplin", "Charlie Chaplin, Paulette Goddard, Jack Oakie", "Commedia, Satira", 125,
    "Un barbiere ebreo smemorato è identico al dittatore di Tomania che perseguita il suo quartiere. Uno scambio di persona offre all'uomo più mite del paese un microfono e una scelta.",
    "barber chair in ghetto shop, inflatable globe floating above dictator office, two identical anonymous moustached silhouettes, giant rally microphone without symbols"),
  film("Quarto potere", 1941, "Orson Welles", "Orson Welles, Joseph Cotten, Dorothy Comingore", "Drammatico, Mistero", 119,
    "Alla morte del magnate Charles Foster Kane, un giornalista indaga sull'ultima parola pronunciata dall'uomo. Testimonianze contraddittorie ricostruiscono l'ascesa e la solitudine dietro un impero mediatico.",
    "childhood sled half-buried in snow, colossal newspaper press, isolated mansion gate, cracked snow globe beside dark microphone, no readable text"),
  film("Casablanca", 1942, "Michael Curtiz", "Humphrey Bogart, Ingrid Bergman, Paul Henreid", "Drammatico, Romantico", 102,
    "A Casablanca, crocevia di profughi e spie, il cinico Rick ritrova Ilsa, amore perduto arrivato con un leader della Resistenza. Due lasciapassare e un aereo in partenza impongono una decisione.",
    "foggy Moroccan airport with propeller plane, café piano and two transit papers, three anonymous silhouettes under trench coats, searchlight sweeping runway"),
  film("La fiamma del peccato", 1944, "Billy Wilder", "Fred MacMurray, Barbara Stanwyck, Edward G. Robinson", "Noir, Crime", 107,
    "Un assicuratore si lascia convincere da una cliente a uccidere il marito e riscuotere una polizza con doppia indennità. Il collega che fiuta le frodi trasforma il piano perfetto in una trappola.",
    "venetian-blind shadows across staircase, woman's anklet beside unsigned insurance policy, noir automobile at railway tracks, match flame and dictation microphone"),
  film("Roma città aperta", 1945, "Roberto Rossellini", "Anna Magnani, Aldo Fabrizi, Marcello Pagliero", "Guerra, Drammatico", 103,
    "Nella Roma occupata, una donna, un prete e una rete di resistenti proteggono un ingegnere braccato. La città affamata vive tra delazioni, rastrellamenti e coraggio quotidiano.",
    "occupied Rome tenement street, priest silhouette hiding resistance printing press, woman running toward military truck, ruined church and children watching, no insignia"),
  film("La vita è meravigliosa", 1946, "Frank Capra", "James Stewart, Donna Reed, Lionel Barrymore", "Fantasy, Drammatico", 130,
    "George Bailey ha passato la vita a rinunciare ai propri sogni per aiutare Bedford Falls. Una notte disperata, un angelo gli mostra come sarebbe il mondo se lui non fosse mai nato.",
    "snowy small-town bridge, lone man and guardian star reflection, savings-and-loan counter, ringing bell beside Christmas tree and crowded family house"),
  film("Ladri di biciclette", 1948, "Vittorio De Sica", "Lamberto Maggiorani, Enzo Staiola, Lianella Carell", "Drammatico", 89,
    "Nella Roma del dopoguerra, Antonio ottiene un lavoro che richiede una bicicletta, ma gliela rubano il primo giorno. Con il figlio Bruno percorre la città cercando un mezzo che vale il futuro della famiglia.",
    "father and small son silhouettes crossing postwar Rome, empty bicycle rack, crowded market of bicycle parts, rain-soaked pawnshop wall stacked with sheets"),
  film("Il terzo uomo", 1949, "Carol Reed", "Joseph Cotten, Alida Valli, Orson Welles", "Noir, Thriller", 104,
    "Uno scrittore arriva nella Vienna occupata per lavorare con l'amico Harry Lime, ma lo trova morto. Versioni incoerenti, una donna sospettosa e un misterioso terzo uomo lo conducono nelle fogne della città.",
    "postwar Vienna sewer tunnels, giant Ferris wheel, long man shadow under tilted streetlamp, zither on café table, four-power checkpoint ruins"),
  film("Rashomon", 1950, "Akira Kurosawa", "Toshiro Mifune, Machiko Kyō, Masayuki Mori", "Drammatico, Mistero", 88,
    "Un delitto nel bosco viene raccontato dal bandito, dalla moglie, dal morto e da un testimone. Ogni versione difende chi parla, lasciando la verità sospesa sotto la pioggia del portale Rashōmon.",
    "ruined Rashomon gate in torrential rain, forest sunbeams splitting into four paths, abandoned samurai sword and rope, four contradictory shadow tableaux"),
  film("Viale del tramonto", 1950, "Billy Wilder", "Gloria Swanson, William Holden, Erich von Stroheim", "Noir, Drammatico", 110,
    "Uno sceneggiatore in rovina diventa ospite e complice di Norma Desmond, diva del muto convinta di poter tornare sullo schermo. La villa isolata trasforma un contratto in prigionia.",
    "decaying Hollywood mansion, empty swimming pool with typewriter floating, grand staircase lit for silent-film star, abandoned studio camera and old reels"),
  film("Cantando sotto la pioggia", 1952, "Stanley Donen, Gene Kelly", "Gene Kelly, Donald O'Connor, Debbie Reynolds", "Musical, Commedia", 103,
    "Hollywood passa dal muto al sonoro e una coppia di star scopre che la voce può distruggere una carriera. Un attore, il suo amico e una giovane cantante cercano di salvare il nuovo film con musica e doppiaggio.",
    "lamppost in heavy rain with anonymous dancer and umbrella, tap shoes splashing, silent-film soundstage becoming microphone booth, three performers behind red curtain"),
  film("Umberto D.", 1952, "Vittorio De Sica", "Carlo Battisti, Maria Pia Casilio, Lina Gennari", "Drammatico", 89,
    "Un pensionato romano non riesce più a pagare l'affitto e rischia di perdere casa, dignità e il cane Flike. La città indifferente riduce la sua resistenza a pochi oggetti e un ultimo legame.",
    "elderly man and tiny terrier silhouettes, sparse Rome pension room, pawned watch and empty soup bowl, crowded train platform at dusk"),
  film("Fronte del porto", 1954, "Elia Kazan", "Marlon Brando, Eva Marie Saint, Karl Malden", "Crime, Drammatico", 108,
    "Terry Malloy, ex pugile e scaricatore, lavora per un sindacato portuale controllato dalla mafia. La morte di un collega e l'incontro con sua sorella lo costringono a scegliere tra silenzio e testimonianza.",
    "foggy New Jersey docks, pigeon coop on rooftop, worn boxing glove beside longshoreman's hook, union office and anonymous dockworker facing hearing microphone"),
  film("La finestra sul cortile", 1954, "Alfred Hitchcock", "James Stewart, Grace Kelly, Thelma Ritter", "Thriller, Mistero", 112,
    "Un fotografo immobilizzato osserva dalla finestra i vicini del cortile e sospetta che uno abbia ucciso la moglie. La curiosità diventa indagine quando la sua compagna entra nell'appartamento sbagliato.",
    "apartment courtyard grid of lit windows, wheelchair and telephoto camera, flashbulbs on table, mysterious suitcase carried at night, woman entering opposite window"),
  film("I sette samurai", 1954, "Akira Kurosawa", "Toshiro Mifune, Takashi Shimura, Keiko Tsushima", "Storico, Azione", 207,
    "Un villaggio di contadini assolda sette samurai senza padrone per difendersi dai banditi che torneranno dopo il raccolto. Preparare il terreno e fidarsi gli uni degli altri sarà difficile quanto combattere.",
    "seven swords planted beside rice field, flooded village barricades, bandit horse silhouettes in rain, farmers and seven anonymous warriors around battle map"),
  film("Gioventù bruciata", 1955, "Nicholas Ray", "James Dean, Natalie Wood, Sal Mineo", "Drammatico", 111,
    "Tre adolescenti soli si incontrano a Los Angeles e costruiscono una famiglia provvisoria lontano dagli adulti. Una sfida automobilistica e la violenza dei coetanei accelerano il loro bisogno di appartenenza.",
    "Griffith Observatory planetarium, red jacket hanging on empty chair, cliff-edge car headlights, three teenage silhouettes inside abandoned mansion"),
  film("Il settimo sigillo", 1957, "Ingmar Bergman", "Max von Sydow, Bengt Ekerot, Gunnar Björnstrand", "Fantasy, Drammatico", 96,
    "Un cavaliere torna dalle Crociate in una Svezia devastata dalla peste e sfida la Morte a scacchi per guadagnare tempo. Il viaggio con una compagnia di attori diventa ricerca di una prova del divino.",
    "medieval knight and black-cloaked Death playing chess on beach, plague procession, traveling actors' wagon, silhouetted dance of figures along ridge"),
  film("La parola ai giurati", 1957, "Sidney Lumet", "Henry Fonda, Lee J. Cobb, Martin Balsam", "Drammatico", 96,
    "Dodici giurati devono decidere la sorte di un ragazzo accusato di omicidio. Un solo dubbio ragionevole trasforma una votazione rapida in un confronto feroce su prove e pregiudizi.",
    "claustrophobic jury room with twelve chairs, one switchblade centered on table, rain on windows, broken wall fan and clock nearing evening"),
  film("Le notti di Cabiria", 1957, "Federico Fellini", "Giulietta Masina, François Périer, Franca Marzi", "Drammatico", 110,
    "Cabiria, prostituta delle periferie romane, conserva una fiducia ostinata nonostante uomini e illusioni la tradiscano. Ogni caduta sembra definitiva, finché una musica sulla strada riapre il mondo.",
    "small woman silhouette with handbag on Rome outskirts, river embankment, empty nightclub stage, candlelit religious procession and musicians on road at dawn"),
  film("Orizzonti di gloria", 1957, "Stanley Kubrick", "Kirk Douglas, Ralph Meeker, Adolphe Menjou", "Guerra, Drammatico", 88,
    "Dopo un assalto impossibile fallito, tre soldati francesi vengono scelti come capri espiatori per codardia. Il colonnello Dax li difende davanti a ufficiali più preoccupati della carriera che della verità.",
    "World War I French trench, opulent general's château table, three empty chairs in execution courtyard, defense papers beside officer medal, no insignia"),
  film("Il ponte sul fiume Kwai", 1957, "David Lean", "William Holden, Alec Guinness, Sessue Hayakawa", "Guerra, Avventura", 161,
    "Prigionieri britannici costruiscono per i giapponesi un ponte ferroviario nella giungla birmana. L'orgoglio del colonnello Nicholson trasforma il lavoro forzato in opera personale, mentre una squadra alleata prepara il sabotaggio.",
    "jungle railway bridge over river, POW construction tools, hidden explosive wire along supports, approaching steam train and officer's whistle"),
  film("La donna che visse due volte", 1958, "Alfred Hitchcock", "James Stewart, Kim Novak, Barbara Bel Geddes", "Thriller, Mistero", 128,
    "Un ex poliziotto con le vertigini viene incaricato di seguire una donna apparentemente ossessionata dal passato. Dopo averla perduta, incontra una sconosciuta e tenta di ricreare l'immagine che lo perseguita.",
    "San Francisco mission bell tower, spiral staircase seen from above, green-lit anonymous woman silhouette, bouquet beside portrait and winding bay road"),
  film("A qualcuno piace caldo", 1959, "Billy Wilder", "Marilyn Monroe, Tony Curtis, Jack Lemmon", "Commedia", 121,
    "Due musicisti assistono a una strage e fuggono travestiti in un'orchestra femminile diretta in Florida. Tra un'ereditiera inventata, un milionario innamorato e una cantante, il travestimento diventa labirinto.",
    "saxophone and double-bass cases, two male musicians disguised from behind in 1920s dresses, Miami hotel bandstand, speedboat and gangsters' car silhouettes"),
  film("I 400 colpi", 1959, "François Truffaut", "Jean-Pierre Léaud, Claire Maurier, Albert Rémy", "Drammatico", 99,
    "Antoine Doinel, adolescente parigino trascurato, alterna scuola, bugie e piccoli furti finché gli adulti lo mandano in riformatorio. La fuga verso il mare è la prima scelta davvero sua.",
    "Paris classroom punishment, stolen typewriter in alley, barred reformatory window, lone teenage silhouette running across beach toward sea"),
  film("Intrigo internazionale", 1959, "Alfred Hitchcock", "Cary Grant, Eva Marie Saint, James Mason", "Thriller, Spy", 136,
    "Un pubblicitario newyorkese viene scambiato per un agente inesistente e trascinato in una rete di spie. Un treno, un aeroplano e il monte Rushmore scandiscono una fuga dove nessuna identità è sicura.",
    "gray-suited anonymous man in empty cornfield chased by crop duster, Mount Rushmore at night, sleeper train compartment, microfilm hidden in sculpture"),
  film("Ben-Hur", 1959, "William Wyler", "Charlton Heston, Stephen Boyd, Jack Hawkins", "Storico, Avventura", 212,
    "Il principe ebreo Giuda Ben-Hur viene tradito dall'amico romano Messala e condannato alle galere. Sopravvive per tornare in Giudea, cercare la famiglia e affrontare il rivale nell'arena.",
    "four-horse chariot racing Roman arena, galley oars and chains, lone star above desert, two rival chariots colliding in dust, no actor likeness"),
  film("Psycho", 1960, "Alfred Hitchcock", "Anthony Perkins, Janet Leigh, Vera Miles", "Horror, Thriller", 109,
    "Dopo aver rubato denaro, Marion Crane si ferma al Bates Motel, gestito da un giovane timido dominato dalla madre. La sua scomparsa porta sorella e investigatore verso la casa sulla collina.",
    "isolated roadside motel beneath gothic hill house, shower curtain silhouette and swirling drain, car sinking into swamp, stuffed bird shadows"),
  film("La dolce vita", 1960, "Federico Fellini", "Marcello Mastroianni, Anita Ekberg, Anouk Aimée", "Drammatico", 174,
    "Marcello, giornalista mondano, attraversa sette notti romane tra divi, aristocratici e miracoli mediatici. Ogni festa promette una vita diversa e lo riporta alla stessa stanchezza.",
    "Trevi Fountain at night, paparazzi flashbulbs, helicopter carrying statue over Rome, decadent terrace party and sea creature on dawn beach"),
  film("L'appartamento", 1960, "Billy Wilder", "Jack Lemmon, Shirley MacLaine, Fred MacMurray", "Commedia, Romantico", 125,
    "Un impiegato presta il proprio appartamento ai dirigenti per le loro relazioni in cambio di avanzamenti. Quando si innamora dell'ascensorista coinvolta col suo capo, deve scegliere che uomo diventare.",
    "endless corporate desks, apartment key rack, tennis racket used as spaghetti strainer, broken mirror and champagne bottle, elevator indicator"),
  film("Fino all'ultimo respiro", 1960, "Jean-Luc Godard", "Jean-Paul Belmondo, Jean Seberg", "Crime, Drammatico", 90,
    "Un piccolo criminale uccide un poliziotto e si nasconde a Parigi dalla giovane americana Patricia. Mentre cerca denaro per fuggire in Italia, il loro gioco d'amore diventa resa dei conti.",
    "Paris boulevard with newspaper seller, stolen convertible, anonymous young couple in tiny apartment, cigarette smoke and police reflections, jump-cut composition"),
  film("L'avventura", 1960, "Michelangelo Antonioni", "Monica Vitti, Gabriele Ferzetti, Lea Massari", "Drammatico, Mistero", 144,
    "Durante una gita alle Eolie, Anna scompare su un'isola rocciosa. L'amica Claudia e il compagno Sandro la cercano, ma l'assenza diventa spazio per un rapporto nuovo e altrettanto instabile.",
    "barren volcanic island beside empty yacht, missing woman's scarf caught on rock, two searcher silhouettes, modernist Sicilian hotel corridor and storm sea"),
  film("West Side Story", 1961, "Robert Wise, Jerome Robbins", "Natalie Wood, Richard Beymer, Rita Moreno", "Musical, Romantico", 152,
    "Due bande rivali si contendono le strade di New York, mentre Tony e Maria si innamorano oltre il confine del quartiere. Danza e violenza trasformano Romeo e Giulietta in una tragedia urbana.",
    "Manhattan fire escapes, two rival dance lines in contrasting colors, chalk boundary across basketball court, rooftop dance and lovers behind fence"),
  film("Lawrence d'Arabia", 1962, "David Lean", "Peter O'Toole, Alec Guinness, Omar Sharif", "Storico, Avventura", 222,
    "L'ufficiale britannico T. E. Lawrence unisce tribù arabe contro l'impero ottomano e diventa leggenda nel deserto. Il trionfo militare confonde sempre più la causa, l'ego e l'identità.",
    "tiny camel rider crossing immense desert, match flame becoming sunrise, derailed Ottoman train, anonymous white-robed figure on dune and Aqaba guns"),
  film("8½", 1963, "Federico Fellini", "Marcello Mastroianni, Claudia Cardinale, Anouk Aimée", "Commedia, Drammatico", 138,
    "Il regista Guido Anselmi dovrebbe iniziare un kolossal, ma non ha più un film né una direzione. Ricordi, amanti, produttori e fantasie invadono il set finché la crisi diventa spettacolo.",
    "unfinished rocket-film set and scaffolding, director's empty chair with megaphone, traffic jam trapped in glass, circus ring joining many anonymous figures"),
  film("Il Gattopardo", 1963, "Luchino Visconti", "Burt Lancaster, Claudia Cardinale, Alain Delon", "Storico, Drammatico", 186,
    "Durante lo sbarco dei garibaldini, il principe di Salina osserva l'aristocrazia siciliana adattarsi al nuovo regno. Il matrimonio tra Tancredi e Angelica garantisce continuità, ma non ferma il tramonto del suo mondo.",
    "Sicilian palace ballroom beneath chandeliers, dusty red-shirt uniform, fading noble crest and fan, sunrise over dry estate after endless dance"),
  film("Il dottor Stranamore", 1964, "Stanley Kubrick", "Peter Sellers, George C. Scott, Sterling Hayden", "Commedia nera, Guerra", 95,
    "Un generale americano ordina di propria iniziativa un attacco nucleare all'URSS. Nella sala di guerra, politici e militari tentano di richiamare i bombardieri prima che entri in funzione l'arma finale.",
    "circular war-room table under giant light ring, B-52 over polar clouds, cowboy hat resting on nuclear bomb, red telephone and doomsday map without text"),
  film("Mary Poppins", 1964, "Robert Stevenson", "Julie Andrews, Dick Van Dyke, David Tomlinson", "Fantasy, Musical", 139,
    "Una governante arriva dal cielo nella casa dei Banks e porta ordine attraverso avventure impossibili. Tra spazzacamini, animali disegnati e aquiloni, anche il padre impara a guardare i figli.",
    "umbrella-carrying nanny silhouette floating over London rooftops, chimney sweeps dancing, carousel horse leaving painted park, carpet bag and repaired kite"),
  film("La battaglia di Algeri", 1966, "Gillo Pontecorvo", "Brahim Hadjadj, Jean Martin, Yacef Saadi", "Storico, Guerra", 121,
    "Ad Algeri il Fronte di Liberazione organizza la guerriglia contro il dominio francese, mentre i paracadutisti rispondono con controllo e tortura. La città diventa campo di battaglia e laboratorio politico.",
    "Casbah alleys and rooftop crowds, woman carrying market basket past checkpoint, paratrooper roadblocks, hidden printing press and city explosions without bodies"),
  film("Il buono, il brutto, il cattivo", 1966, "Sergio Leone", "Clint Eastwood, Lee Van Cleef, Eli Wallach", "Western", 178,
    "Tre pistoleri cercano un tesoro confederato sepolto durante la guerra civile, alleandosi e tradendosi a ogni tappa. Il viaggio culmina in un cimitero circolare dove soltanto uno conosce il nome sulla tomba.",
    "three anonymous gunfighter silhouettes forming triangle in circular cemetery, hidden gold grave, Civil War bridge exploding in distance, three hats and pocket watch"),
  film("Persona", 1966, "Ingmar Bergman", "Bibi Andersson, Liv Ullmann, Margaretha Krook", "Drammatico", 83,
    "Un'attrice smette improvvisamente di parlare e viene affidata a un'infermiera in una casa sul mare. Il silenzio assorbe confessioni e identità, fino a rendere indistinguibili le due donne.",
    "two anonymous women's profiles merging into one face, cracked film strip and projector, stark seaside cottage, hand reaching toward cinema screen, black-and-white"),
  film("Il laureato", 1967, "Mike Nichols", "Dustin Hoffman, Anne Bancroft, Katharine Ross", "Commedia, Drammatico", 106,
    "Benjamin torna dal college senza sapere cosa fare e viene sedotto dalla moglie di un socio del padre. Quando si innamora della figlia di lei, la ribellione contro il futuro programmato diventa una corsa.",
    "young man underwater in suburban pool wearing scuba mask, hotel room key and older woman's stocking on chair, red sports car racing toward church, bus escape silhouettes"),
  film("2001: Odissea nello spazio", 1968, "Stanley Kubrick", "Keir Dullea, Gary Lockwood, William Sylvester", "Fantascienza", 149,
    "Un monolito compare all'alba dell'umanità e un altro viene scoperto sulla Luna. La missione Discovery segue il segnale verso Giove, sorvegliata da un computer che considera l'equipaggio una minaccia.",
    "black monolith on lunar plain, rotating wheel space station, anonymous astronaut entering psychedelic star gate, single red artificial-intelligence lens, no exact spacecraft design"),
  film("C'era una volta il West", 1968, "Sergio Leone", "Henry Fonda, Charles Bronson, Claudia Cardinale", "Western", 165,
    "Una vedova eredita una terra decisiva per la ferrovia e diventa bersaglio di un sicario. Un bandito e uno straniero con l'armonica si schierano attorno a lei, ciascuno con un conto aperto.",
    "lonely frontier railway station, harmonica on wooden crate, water tower and unfinished tracks, widow silhouette facing three gunmen, steam train crossing desert"),
  film("Il pianeta delle scimmie", 1968, "Franklin J. Schaffner", "Charlton Heston, Roddy McDowall, Kim Hunter", "Fantascienza, Avventura", 112,
    "Astronauti precipitati su un pianeta sconosciuto scoprono una società governata da scimmie parlanti, dove gli umani sono bestie mute. Taylor cerca una prova che ribalti l'ordine ufficiale.",
    "crashed spacecraft beside desert lake, anonymous astronaut captured near ape-ruled city silhouettes, archaeological cave, ruined Statue of Liberty on beach"),
  film("La notte dei morti viventi", 1968, "George A. Romero", "Duane Jones, Judith O'Dea, Karl Hardman", "Horror", 96,
    "I morti tornano a camminare e un gruppo di sconosciuti si barrica in una casa di campagna. Paura e conflitti interni rendono il rifugio pericoloso quanto ciò che preme alle finestre.",
    "isolated farmhouse with boarded windows, cemetery zombie silhouettes, television static reporting crisis, cellar door and burning field at night, no gore"),
  film("Arancia meccanica", 1971, "Stanley Kubrick", "Malcolm McDowell, Patrick Magee, Michael Bates", "Fantascienza, Drammatico", 136,
    "Alex guida una banda di giovani violenti e adora Beethoven, finché lo Stato lo sottopone a una cura che gli impedisce fisicamente di scegliere il male. La rieducazione diventa un'altra forma di brutalità.",
    "four anonymous bowler-hatted youth silhouettes in white, futuristic milk bar, Beethoven record beside cane, institutional cinema chair with eye apparatus shown non-graphically"),
  film("Il padrino", 1972, "Francis Ford Coppola", "Marlon Brando, Al Pacino, James Caan", "Crime, Drammatico", 175,
    "Durante il matrimonio della figlia, il boss Vito Corleone riceve richieste nel suo studio. Un attentato costringe il figlio Michael, finora estraneo agli affari, a entrare nella famiglia.",
    "Italian-American wedding lights outside dark office, orange and cat on patriarch's desk, three brothers' silhouettes, Sicilian car on dusty road, no actor likeness"),
  film("Solaris", 1972, "Andrej Tarkovskij", "Donatas Banionis, Natal'ja Bondarčuk, Jüri Järvet", "Fantascienza, Drammatico", 167,
    "Uno psicologo raggiunge una stazione orbitale in crisi sopra l'oceano di Solaris. Il pianeta materializza ricordi e sensi di colpa, restituendogli una donna morta che non sa di esserlo.",
    "decaying orbital station above living ocean planet, library objects floating weightless, rain falling inside room, duplicated woman silhouette and childhood island reflected below"),
  film("L'esorcista", 1973, "William Friedkin", "Ellen Burstyn, Linda Blair, Max von Sydow", "Horror", 122,
    "Una ragazza cambia comportamento dopo aver giocato con una tavoletta spiritica e i medici non trovano spiegazioni. La madre chiede aiuto a due sacerdoti, uno dei quali sta perdendo la fede.",
    "Georgetown townhouse at night, priest silhouette beneath lamppost facing lit bedroom window, long outdoor staircase, medical scans and exorcism case on table, no child shown"),
  film("Amarcord", 1973, "Federico Fellini", "Pupella Maggio, Armando Brancia, Magali Noël", "Commedia, Drammatico", 123,
    "In una cittadina romagnola degli anni Trenta, Titta attraversa scuola, famiglia, desideri e rituali collettivi. Ricordi veri e inventati compongono un anno di provincia sotto il fascismo.",
    "Adriatic seaside town in snow, peacock spreading tail, giant ocean liner at night, spring bonfire and schoolboy silhouettes, parade without political symbols"),
  film("La conversazione", 1974, "Francis Ford Coppola", "Gene Hackman, John Cazale, Allen Garfield", "Thriller", 113,
    "Un esperto di intercettazioni registra una coppia in una piazza e teme che il nastro prepari un omicidio. Ossessionato da un vecchio errore, riascolta le parole finché il significato cambia.",
    "crowded Union Square seen through telephoto lens, saxophone beside surveillance tapes and headphones, translucent raincoat, dismantled apartment searching for hidden bug"),
  film("Chinatown", 1974, "Roman Polanski", "Jack Nicholson, Faye Dunaway, John Huston", "Noir, Mistero", 130,
    "Un investigatore privato segue un caso di adulterio e scopre una guerra segreta per l'acqua di Los Angeles. Dietro dighe, terreni e una famiglia potente si nasconde una verità più antica.",
    "dry Los Angeles aqueduct pouring water at night, broken eyeglasses in salt pond, orange grove, noir detective silhouette and city street mysteriously flooding"),
  film("Il padrino - Parte II", 1974, "Francis Ford Coppola", "Al Pacino, Robert De Niro, Diane Keaton", "Crime, Drammatico", 202,
    "Michael Corleone difende l'impero di famiglia a Lake Tahoe e a Cuba, isolandosi da ogni affetto. In parallelo, il giovane Vito arriva a New York e costruisce il potere che il figlio erediterà.",
    "split-era composition: immigrant boy at Ellis Island and dark Lake Tahoe office, Little Italy market, Havana New Year fireworks, oranges and empty family table"),
  film("Qualcuno volò sul nido del cuculo", 1975, "Miloš Forman", "Jack Nicholson, Louise Fletcher, Will Sampson", "Drammatico", 133,
    "Randle McMurphy si finge malato per evitare il carcere e finisce in un reparto psichiatrico governato dall'infermiera Ratched. La sua energia contagia i pazienti e provoca uno scontro sul controllo.",
    "psychiatric ward card table, locked medication window, stolen fishing boat with patient silhouettes, heavy hydrotherapy control panel and broken window at dawn"),
  film("Lo squalo", 1975, "Steven Spielberg", "Roy Scheider, Robert Shaw, Richard Dreyfuss", "Thriller, Avventura", 124,
    "Uno squalo attacca i bagnanti di Amity e il sindaco rifiuta di chiudere le spiagge. Il capo della polizia parte in mare con un biologo e un cacciatore per fermarlo.",
    "crowded summer beach above enormous shark shadow, yellow flotation barrels, small fishing boat with three anonymous men, police badge and broken cage underwater"),
  film("Fantozzi", 1975, "Luciano Salce", "Paolo Villaggio, Anna Mazzamauro, Gigi Reder", "Commedia", 108,
    "Il ragionier Ugo Fantozzi sopravvive a capi sadici, colleghi servili e rituali aziendali disumani. Ogni tentativo di dignità diventa una catastrofe domestica o professionale.",
    "tiny accountant at colossal office desk, punch clock and endless paperwork, commuter bus chased through rain, small car under personal storm cloud, no actor likeness"),
  film("Taxi Driver", 1976, "Martin Scorsese", "Robert De Niro, Jodie Foster, Cybill Shepherd", "Drammatico, Thriller", 114,
    "Travis Bickle guida un taxi di notte nella New York che disprezza e annota la propria solitudine. L'incontro con una ragazza sfruttata trasforma il bisogno di purezza in una missione violenta.",
    "yellow cab in rainy Times Square, sleepless eyes reflected in rearview mirror without likeness, empty campaign office, mohawk shadow and steam rising from street"),
  film("Obsession", 1976, "Brian De Palma", "Cliff Robertson, Geneviève Bujold, John Lithgow", "Thriller, Mistero, Drammatico", 98,
    "Nel 1959 l'imprenditore di New Orleans Michael Courtland perde moglie e figlia durante un rapimento finito tragicamente. Sedici anni dopo, a Firenze, incontra Sandra, una giovane identica alla moglie: il tentativo di ricreare il passato lo trascina in un intrigo di colpa, desiderio e inganno.",
    "anonymous grieving man facing two identical female silhouettes divided by cracked mirror, Florence cathedral and New Orleans balcony dissolving together, gold wedding ring and torn photograph"),
  film("Rocky", 1976, "John G. Avildsen", "Sylvester Stallone, Talia Shire, Burgess Meredith", "Drammatico, Sport", 120,
    "Rocky Balboa, pugile di periferia che vive di incontri minori, riceve la possibilità di sfidare il campione dei pesi massimi. Allenarsi diventa il modo di dimostrare di poter restare in piedi.",
    "anonymous boxer running up Philadelphia museum steps at dawn, worn gloves in meat locker, neighborhood gym ring, raw eggs and small apartment window"),
  film("Quinto potere", 1976, "Sidney Lumet", "Faye Dunaway, William Holden, Peter Finch", "Drammatico, Satira", 121,
    "Un anchorman prossimo al licenziamento annuncia in diretta che si ucciderà e diventa un fenomeno di ascolti. La rete trasforma la sua rabbia in formato televisivo, finché anche la follia deve rispettare l'audience.",
    "news anchor desk under harsh lights, wall of television screens, rain-soaked silhouette shouting at window, control room ratings graph without text and corporate boardroom"),
  film("Guerre stellari", 1977, "George Lucas", "Mark Hamill, Harrison Ford, Carrie Fisher", "Fantascienza, Avventura", 121,
    "Un ragazzo di un pianeta desertico entra nella ribellione contro un impero galattico dopo aver trovato un messaggio affidato a due droidi. Una principessa prigioniera e una stazione da battaglia attendono.",
    "twin suns above desert farm, anonymous robed youth with two small original robot silhouettes, generic starfighters attacking spherical battle station, smuggler ship in hangar, no exact designs"),
  film("Suspiria", 1977, "Dario Argento", "Jessica Harper, Stefania Casini, Alida Valli", "Horror", 99,
    "Una ballerina americana arriva in una prestigiosa accademia tedesca durante un temporale. Corridoi impossibili, sparizioni e una direttrice invisibile rivelano che la scuola custodisce altro.",
    "German dance academy in saturated red and blue storm, abandoned ballet shoes, art-nouveau stained glass, secret corridor behind mirrored wall and black feather shadows"),
  film("Halloween - La notte delle streghe", 1978, "John Carpenter", "Jamie Lee Curtis, Donald Pleasence, Nick Castle", "Horror", 91,
    "Un assassino evade dall'ospedale e torna nella cittadina dove uccise da bambino. Nella notte di Halloween segue una babysitter mentre il medico che lo conosce tenta di trovarlo.",
    "quiet suburban house on Halloween night, carved pumpkin foreground, pale featureless mask shadow behind hedge, babysitter window and station wagon under streetlamp"),
  film("Il cacciatore", 1978, "Michael Cimino", "Robert De Niro, Christopher Walken, Meryl Streep", "Guerra, Drammatico", 183,
    "Tre operai della Pennsylvania partono per il Vietnam dopo un lungo matrimonio russo-ortodosso. La prigionia e il ritorno dividono per sempre amicizia, lavoro e rituali di caccia.",
    "Pennsylvania steel-mill town wedding crowns, three empty chairs beside hunting gear, mountain deer at dawn, POW bamboo cage silhouette and roulette table shown without violence"),
  film("Apocalypse Now", 1979, "Francis Ford Coppola", "Martin Sheen, Marlon Brando, Robert Duvall", "Guerra, Drammatico", 147,
    "Il capitano Willard risale un fiume cambogiano per eliminare il colonnello Kurtz, che ha creato un regno personale nella giungla. Ogni tappa dissolve un altro confine tra missione e follia.",
    "helicopters crossing orange jungle fire, patrol boat moving upriver, temple compound silhouette, ceiling fan blending with rotor and dossier beside map, no actor likeness"),
  film("Alien", 1979, "Ridley Scott", "Sigourney Weaver, Tom Skerritt, John Hurt", "Horror, Fantascienza", 117,
    "L'equipaggio di un cargo spaziale risponde a un segnale su un pianeta deserto e porta a bordo una forma di vita sconosciuta. Nei corridoi della nave, l'organismo cresce e caccia.",
    "industrial cargo spaceship corridor, vast egg chamber on alien planetoid, anonymous astronaut helmet under dripping pipes, original biomechanical creature shadow, airlock warning lights"),
  film("Shining", 1980, "Stanley Kubrick", "Jack Nicholson, Shelley Duvall, Danny Lloyd", "Horror", 146,
    "Uno scrittore accetta di sorvegliare con la famiglia un albergo isolato per l'inverno. La neve chiude ogni uscita mentre corridoi, visioni e la storia dell'hotel prendono possesso di lui.",
    "snowbound mountain hotel, hedge maze from above, child's tricycle in patterned corridor, twin girl silhouettes far away, typewriter and axe shadow, no faces"),
  film("The Blues Brothers", 1980, "John Landis", "John Belushi, Dan Aykroyd, Cab Calloway", "Commedia, Musica", 133,
    "Jake ed Elwood rimettono insieme la vecchia band per salvare l'orfanotrofio dove sono cresciuti. La missione per conto di Dio attraversa concerti, inseguimenti e mezza polizia dell'Illinois.",
    "two anonymous black-suited silhouettes with hats and sunglasses, battered black sedan airborne over bridge, blues band stage, enormous police-car pileup, no logos"),
  film("Toro scatenato", 1980, "Martin Scorsese", "Robert De Niro, Cathy Moriarty, Joe Pesci", "Biografico, Sport", 129,
    "Il pugile Jake LaMotta porta sul ring rabbia e disciplina, ma fuori trasforma gelosia e paranoia in autodistruzione. Vittorie e sconfitte misurano il prezzo di non saper smettere di combattere.",
    "black-and-white boxing ring in smoke, anonymous robe-clad boxer under camera flashes, smashed dressing-room mirror, empty nightclub microphone years later"),
  film("I predatori dell'arca perduta", 1981, "Steven Spielberg", "Harrison Ford, Karen Allen, Paul Freeman", "Avventura", 115,
    "Nel 1936 l'archeologo Indiana Jones cerca l'Arca dell'Alleanza prima dei nazisti. Dal tempio nella giungla al deserto egiziano, ogni reliquia apre una trappola.",
    "jungle temple with giant rolling boulder, generic fedora and coiled whip beside golden idol, desert convoy, ancient sealed chest glowing inside dig site, no actor likeness or insignia"),
  film("Blade Runner", 1982, "Ridley Scott", "Harrison Ford, Rutger Hauer, Sean Young", "Fantascienza, Noir", 117,
    "Nella Los Angeles del 2019, un ex poliziotto deve ritirare quattro replicanti tornati sulla Terra. L'indagine mette in dubbio la differenza tra memoria artificiale e vita.",
    "rainy neon Los Angeles canyon, origami unicorn on detective desk, enormous eye reflection, generic flying car above umbrella crowds, rooftop in downpour, no actor likeness"),
  film("E.T. l'extra-terrestre", 1982, "Steven Spielberg", "Henry Thomas, Dee Wallace, Drew Barrymore", "Fantascienza, Avventura", 115,
    "Un alieno rimasto sulla Terra viene nascosto da Elliott nella casa di periferia. Mentre la loro salute si lega, i ragazzi costruiscono un modo per chiamare la nave prima che gli adulti lo trovino.",
    "child bicycle silhouette crossing full moon with small original alien passenger, suburban bedroom transmitter, forest landing lights, red hood and glowing fingertip without exact character design"),
  film("C'era una volta in America", 1984, "Sergio Leone", "Robert De Niro, James Woods, Elizabeth McGovern", "Crime, Drammatico", 229,
    "Un ex gangster torna a New York dopo decenni e ricompone l'amicizia con Max, dagli anni del ghetto al proibizionismo. Memoria, colpa e tradimento rendono incerto anche ciò che sembra ricordato.",
    "Manhattan Bridge framed by tenement street, four boy silhouettes at 1920s waterfront, prohibition speakeasy, opium pipe, locked station suitcase and empty banquet hall"),
  film("Terminator", 1984, "James Cameron", "Arnold Schwarzenegger, Linda Hamilton, Michael Biehn", "Fantascienza, Azione", 107,
    "Un cyborg viene inviato dal futuro per uccidere Sarah Connor prima che dia alla luce il capo della resistenza. Un soldato umano attraversa il tempo per proteggerla nella Los Angeles del 1984.",
    "original skeletal machine silhouette with single red eye, blue time-arrival sphere in 1984 alley, nightclub chase, future battlefield ruins and tanker truck, no exact character likeness"),
  film("Ghostbusters", 1984, "Ivan Reitman", "Bill Murray, Dan Aykroyd, Sigourney Weaver", "Commedia, Fantasy", 105,
    "Tre scienziati aprono a New York un servizio di disinfestazione paranormale e il lavoro esplode. Un palazzo sulla Central Park West diventa il portale per un'entità che minaccia la città.",
    "converted firehouse headquarters, four anonymous jumpsuit silhouettes crossing colored energy beams into ghost trap, white hearse-like car, rooftop portal and giant harmless marshmallow figure shadow, no logos"),
  film("Ritorno al futuro", 1985, "Robert Zemeckis", "Michael J. Fox, Christopher Lloyd, Lea Thompson", "Fantascienza, Commedia", 116,
    "Marty McFly viene spedito dal 1985 al 1955 con la macchina del tempo di Doc Brown e impedisce per errore l'incontro dei genitori. Deve rimetterli insieme e catturare un fulmine per tornare.",
    "flaming tire tracks, stainless unbranded sports car silhouette, clock tower struck by lightning, skateboard and 1950s dance, anonymous teen and wild-haired scientist from behind"),
  film("Aliens - Scontro finale", 1986, "James Cameron", "Sigourney Weaver, Michael Biehn, Paul Reiser", "Fantascienza, Azione", 137,
    "Ripley torna sul pianeta dove incontrò la creatura insieme a una squadra di marines, dopo che una colonia smette di rispondere. Trova una bambina sopravvissuta e un nido molto più grande.",
    "abandoned space-colony corridor, anonymous woman in industrial power-loader facing original alien queen shadow, egg nest, small child hiding under floor, dropship lights, no exact designs"),
  film("Nuovo Cinema Paradiso", 1988, "Giuseppe Tornatore", "Philippe Noiret, Salvatore Cascio, Jacques Perrin", "Drammatico", 124,
    "Un regista affermato torna in Sicilia dopo la morte di Alfredo, proiezionista che gli insegnò ad amare il cinema. I ricordi del paese e della sala Paradiso ricompongono il prezzo della partenza.",
    "Sicilian town-square outdoor screening, projector beam joining child and elderly projectionist silhouettes, burning film strip, abandoned cinema seats and montage of censored kisses without faces"),
  film("Trappola di cristallo", 1988, "John McTiernan", "Bruce Willis, Alan Rickman, Bonnie Bedelia", "Azione, Thriller", 132,
    "Un poliziotto di New York arriva a Los Angeles per la festa aziendale della moglie e resta intrappolato in un grattacielo occupato da rapinatori. Scalzo e isolato, usa piani tecnici e radio per resistere.",
    "Los Angeles skyscraper at Christmas, bloody-but-non-graphic barefoot footprints across broken glass, fire hose tied to roof, police car below and office radio, no actor likeness"),
  film("Il mio vicino Totoro", 1988, "Hayao Miyazaki", "Noriko Hidaka, Chika Sakamoto, Hitoshi Takagi (voci)", "Animazione, Fantasy", 86,
    "Due sorelle si trasferiscono in campagna mentre la madre è in ospedale e scoprono spiriti gentili nel bosco. Il più grande le accompagna tra pioggia, semi e un viaggio notturno.",
    "two sisters at rural bus stop in rain, huge original round forest-spirit silhouette with leaf umbrella, sprouting seeds, many-legged cat-shaped night bus suggested but not copied"),
  film("Quei bravi ragazzi", 1990, "Martin Scorsese", "Ray Liotta, Robert De Niro, Joe Pesci", "Crime, Drammatico", 145,
    "Henry Hill sogna fin da ragazzo la vita dei gangster e scala la famiglia mafiosa tra locali, rapine e privilegi. Droga, paranoia e tradimenti trasformano l'appartenenza in una gabbia.",
    "nightclub kitchen back entrance with three anonymous suited silhouettes, red restaurant booth, airport cargo plane and money bags, frantic helicopter reflected in rearview mirror, no likeness"),
  film("Il silenzio degli innocenti", 1991, "Jonathan Demme", "Jodie Foster, Anthony Hopkins, Scott Glenn", "Thriller", 118,
    "La recluta dell'FBI Clarice Starling chiede aiuto al detenuto Hannibal Lecter per trovare un serial killer. Ogni colloquio nella cella di vetro diventa uno scambio tra indagine e memoria.",
    "anonymous FBI trainee at glass prison cell, death's-head moth, lambs behind misty barn fence, night-vision green basement, case files without readable text"),
  film("Terminator 2 - Il giorno del giudizio", 1991, "James Cameron", "Arnold Schwarzenegger, Linda Hamilton, Edward Furlong", "Fantascienza, Azione", 137,
    "Due cyborg arrivano dal futuro sulle tracce del giovane John Connor: uno per eliminarlo, l'altro per proteggerlo. Sarah tenta di impedire la nascita dell'intelligenza che distruggerà il mondo.",
    "motorcycle and truck chase through concrete canal, liquid-metal humanoid silhouette, anonymous boy beside protective machine, nuclear playground vision and molten-steel factory, no exact likeness"),
  film("Le iene", 1992, "Quentin Tarantino", "Harvey Keitel, Tim Roth, Michael Madsen", "Crime, Thriller", 99,
    "Dopo una rapina fallita, criminali che si conoscono solo con nomi di colore si ritrovano in un magazzino. Uno di loro è una spia e ogni versione dei fatti restringe il cerchio.",
    "six colored neckties laid on warehouse table, diamond bag and empty car trunk, anonymous black-suited silhouettes arguing under skylight, police radio and breakfast diner cups"),
  film("Schindler's List", 1993, "Steven Spielberg", "Liam Neeson, Ben Kingsley, Ralph Fiennes", "Storico, Drammatico", 195,
    "L'industriale Oskar Schindler sfrutta inizialmente la guerra per arricchirsi, poi usa fabbrica, denaro e relazioni per salvare i lavoratori ebrei dalla deportazione. Una lista diventa confine tra vita e morte.",
    "black-and-white Krakow factory, typewriter creating long list without readable names, tiny red coat crossing crowd, empty suitcases and candles, no violence or actor likeness"),
  film("Jurassic Park", 1993, "Steven Spielberg", "Sam Neill, Laura Dern, Jeff Goldblum", "Fantascienza, Avventura", 127,
    "Un miliardario invita scienziati e nipoti a visitare un parco di dinosauri clonati prima dell'apertura. Un sabotaggio spegne le recinzioni e trasforma il tour in sopravvivenza.",
    "tropical island gate without logo, giant original tyrannosaur silhouette between jeep headlights, rippling water cup, electrified fence and cracked dinosaur egg"),
  film("Le ali della libertà", 1994, "Frank Darabont", "Tim Robbins, Morgan Freeman, Bob Gunton", "Drammatico", 142,
    "Andy Dufresne viene condannato per un omicidio che nega di aver commesso e passa decenni nel carcere di Shawshank. L'amicizia con Red e una pazienza incrollabile tengono aperta l'idea della libertà.",
    "prison yard and library, tiny rock hammer hidden inside Bible without readable text, tunnel behind pin-up poster, anonymous man raising arms in rain outside sewer pipe"),
  film("Forrest Gump", 1994, "Robert Zemeckis", "Tom Hanks, Robin Wright, Gary Sinise", "Drammatico, Commedia", 142,
    "Forrest racconta da una panchina una vita attraversata correndo: football, Vietnam, ping-pong e pesca dei gamberi. La sua costante è Jenny, amata anche quando prende strade lontane.",
    "white feather landing on bus-stop bench, worn running shoes crossing America, shrimp boat in storm, ping-pong paddle and Vietnam rain, box of chocolates without branding"),
  film("Pulp Fiction", 1994, "Quentin Tarantino", "John Travolta, Uma Thurman, Samuel L. Jackson", "Crime, Commedia nera", 154,
    "Le storie di due sicari, della moglie di un boss, di un pugile e di una coppia di rapinatori si incrociano a Los Angeles fuori ordine. Una valigetta luminosa passa di mano mentre caso e scelta cambiano i finali.",
    "Los Angeles diner booth, glowing briefcase, two anonymous black-suited silhouettes, twist-dance floor, red convertible and gold watch, no actor likeness or logos"),
];
