// Seed del catalogo: film noti ~1985-2026, solo fatti (titolo, anno, regista, attori, generi).
// Idempotente: INSERT OR IGNORE sulla coppia (titolo, anno).
// Uso: node scripts/seed-movies.mjs
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import fs from "node:fs";
import path from "node:path";
import { CLASSIC_FILMS } from "./classic-films.mjs";

// [titolo, anno, regista, attori, generi]
const FILMS = [
  ["Scandalosa Gilda", 1985, "Gabriele Lavia", "Monica Guerritore, Gabriele Lavia, Pina Cei", "Drammatico, Erotico"],
  ["Seven", 1995, "David Fincher", "Brad Pitt, Morgan Freeman, Kevin Spacey", "Thriller"],
  ["Heat - La sfida", 1995, "Michael Mann", "Al Pacino, Robert De Niro, Val Kilmer", "Crime, Thriller"],
  ["I soliti sospetti", 1995, "Bryan Singer", "Kevin Spacey, Gabriel Byrne", "Thriller"],
  ["Toy Story", 1995, "John Lasseter", "Tom Hanks, Tim Allen (voci)", "Animazione"],
  ["Braveheart", 1995, "Mel Gibson", "Mel Gibson, Sophie Marceau", "Storico, Azione"],
  ["Fargo", 1996, "Joel Coen", "Frances McDormand, William H. Macy, Steve Buscemi", "Crime, Commedia nera"],
  ["Trainspotting", 1996, "Danny Boyle", "Ewan McGregor, Robert Carlyle", "Drammatico"],
  ["Independence Day", 1996, "Roland Emmerich", "Will Smith, Jeff Goldblum", "Fantascienza, Azione"],
  ["Titanic", 1997, "James Cameron", "Leonardo DiCaprio, Kate Winslet", "Drammatico, Romantico"],
  ["La vita è bella", 1997, "Roberto Benigni", "Roberto Benigni, Nicoletta Braschi", "Drammatico"],
  ["Full Monty - Squattrinati organizzati", 1997, "Peter Cattaneo", "Robert Carlyle, Mark Addy", "Commedia"],
  ["Men in Black", 1997, "Barry Sonnenfeld", "Will Smith, Tommy Lee Jones", "Fantascienza, Commedia"],
  ["L.A. Confidential", 1997, "Curtis Hanson", "Russell Crowe, Guy Pearce, Kim Basinger", "Noir, Crime"],
  ["Principessa Mononoke", 1997, "Hayao Miyazaki", "", "Animazione, Fantasy"],
  ["Salvate il soldato Ryan", 1998, "Steven Spielberg", "Tom Hanks, Matt Damon", "Guerra, Drammatico"],
  ["The Truman Show", 1998, "Peter Weir", "Jim Carrey, Ed Harris", "Drammatico, Commedia"],
  ["Il grande Lebowski", 1998, "Joel Coen", "Jeff Bridges, John Goodman, Julianne Moore", "Commedia"],
  ["Lock & Stock - Pazzi scatenati", 1998, "Guy Ritchie", "Jason Flemyng, Jason Statham, Vinnie Jones", "Crime, Commedia"],
  ["Matrix", 1999, "Lana e Lilly Wachowski", "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss", "Fantascienza, Azione"],
  ["Fight Club", 1999, "David Fincher", "Edward Norton, Brad Pitt, Helena Bonham Carter", "Drammatico, Thriller"],
  ["Il sesto senso", 1999, "M. Night Shyamalan", "Bruce Willis, Haley Joel Osment", "Thriller"],
  ["American Beauty", 1999, "Sam Mendes", "Kevin Spacey, Annette Bening", "Drammatico"],
  ["Il miglio verde", 1999, "Frank Darabont", "Tom Hanks, Michael Clarke Duncan", "Drammatico"],
  ["Il gladiatore", 2000, "Ridley Scott", "Russell Crowe, Joaquin Phoenix", "Storico, Azione"],
  ["Memento", 2000, "Christopher Nolan", "Guy Pearce, Carrie-Anne Moss", "Thriller"],
  ["Snatch - Lo strappo", 2000, "Guy Ritchie", "Jason Statham, Brad Pitt, Benicio del Toro", "Crime, Commedia"],
  ["Cast Away", 2000, "Robert Zemeckis", "Tom Hanks, Helen Hunt", "Drammatico, Avventura"],
  ["La tigre e il dragone", 2000, "Ang Lee", "Chow Yun-fat, Michelle Yeoh, Zhang Ziyi", "Wuxia, Avventura"],
  ["Requiem for a Dream", 2000, "Darren Aronofsky", "Ellen Burstyn, Jared Leto, Jennifer Connelly", "Drammatico"],
  ["Il favoloso mondo di Amélie", 2001, "Jean-Pierre Jeunet", "Audrey Tautou, Mathieu Kassovitz", "Commedia, Romantico"],
  ["Il Signore degli Anelli - La Compagnia dell'Anello", 2001, "Peter Jackson", "Elijah Wood, Ian McKellen, Viggo Mortensen", "Fantasy, Avventura"],
  ["Harry Potter e la pietra filosofale", 2001, "Chris Columbus", "Daniel Radcliffe, Emma Watson, Rupert Grint", "Fantasy"],
  ["Shrek", 2001, "Andrew Adamson, Vicky Jenson", "Mike Myers, Eddie Murphy (voci)", "Animazione, Commedia"],
  ["A Beautiful Mind", 2001, "Ron Howard", "Russell Crowe, Jennifer Connelly", "Biografico, Drammatico"],
  ["La stanza del figlio", 2001, "Nanni Moretti", "Nanni Moretti, Laura Morante", "Drammatico"],
  ["Mulholland Drive", 2001, "David Lynch", "Naomi Watts, Laura Harring", "Thriller, Mistero"],
  ["La città incantata", 2001, "Hayao Miyazaki", "", "Animazione, Fantasy"],
  ["Donnie Darko", 2001, "Richard Kelly", "Jake Gyllenhaal, Jena Malone", "Fantascienza, Drammatico"],
  ["Il pianista", 2002, "Roman Polanski", "Adrien Brody", "Drammatico, Guerra"],
  ["City of God - La città di Dio", 2002, "Fernando Meirelles", "Alexandre Rodrigues, Leandro Firmino", "Crime, Drammatico"],
  ["Il Signore degli Anelli - Le due torri", 2002, "Peter Jackson", "Elijah Wood, Viggo Mortensen, Andy Serkis", "Fantasy, Avventura"],
  ["Prova a prendermi", 2002, "Steven Spielberg", "Leonardo DiCaprio, Tom Hanks", "Biografico, Commedia"],
  ["Il Signore degli Anelli - Il ritorno del re", 2003, "Peter Jackson", "Elijah Wood, Viggo Mortensen, Ian McKellen", "Fantasy, Avventura"],
  ["Lost in Translation - L'amore tradotto", 2003, "Sofia Coppola", "Bill Murray, Scarlett Johansson", "Drammatico, Commedia"],
  ["Kill Bill: Volume 1", 2003, "Quentin Tarantino", "Uma Thurman, Lucy Liu", "Azione"],
  ["Alla ricerca di Nemo", 2003, "Andrew Stanton", "Albert Brooks, Ellen DeGeneres (voci)", "Animazione"],
  ["Old Boy", 2003, "Park Chan-wook", "Choi Min-sik, Yoo Ji-tae", "Thriller"],
  ["La meglio gioventù", 2003, "Marco Tullio Giordana", "Luigi Lo Cascio, Alessio Boni", "Drammatico"],
  ["Se mi lasci ti cancello", 2004, "Michel Gondry", "Jim Carrey, Kate Winslet", "Drammatico, Fantascienza"],
  ["Million Dollar Baby", 2004, "Clint Eastwood", "Hilary Swank, Clint Eastwood, Morgan Freeman", "Drammatico, Sport"],
  ["Gli Incredibili", 2004, "Brad Bird", "Craig T. Nelson, Holly Hunter (voci)", "Animazione, Azione"],
  ["Le conseguenze dell'amore", 2004, "Paolo Sorrentino", "Toni Servillo, Olivia Magnani", "Drammatico"],
  ["Il castello errante di Howl", 2004, "Hayao Miyazaki", "", "Animazione, Fantasy"],
  ["Batman Begins", 2005, "Christopher Nolan", "Christian Bale, Michael Caine, Liam Neeson", "Azione"],
  ["I segreti di Brokeback Mountain", 2005, "Ang Lee", "Heath Ledger, Jake Gyllenhaal", "Drammatico, Romantico"],
  ["V per Vendetta", 2005, "James McTeigue", "Natalie Portman, Hugo Weaving", "Fantascienza, Thriller"],
  ["La fabbrica di cioccolato", 2005, "Tim Burton", "Johnny Depp, Freddie Highmore", "Fantasy, Commedia"],
  ["The Departed - Il bene e il male", 2006, "Martin Scorsese", "Leonardo DiCaprio, Matt Damon, Jack Nicholson", "Crime, Thriller"],
  ["Il labirinto del fauno", 2006, "Guillermo del Toro", "Ivana Baquero, Sergi López", "Fantasy, Drammatico"],
  ["Le vite degli altri", 2006, "Florian Henckel von Donnersmarck", "Ulrich Mühe, Martina Gedeck", "Drammatico"],
  ["The Prestige", 2006, "Christopher Nolan", "Hugh Jackman, Christian Bale, Scarlett Johansson", "Thriller, Mistero"],
  ["Little Miss Sunshine", 2006, "Jonathan Dayton, Valerie Faris", "Steve Carell, Toni Collette, Abigail Breslin", "Commedia, Drammatico"],
  ["Il diavolo veste Prada", 2006, "David Frankel", "Meryl Streep, Anne Hathaway, Emily Blunt", "Commedia"],
  ["Casino Royale", 2006, "Martin Campbell", "Daniel Craig, Eva Green", "Azione, Spy"],
  ["Borat", 2006, "Larry Charles", "Sacha Baron Cohen", "Commedia"],
  ["Notte prima degli esami", 2006, "Fausto Brizzi", "Nicolas Vaporidis, Giorgio Faletti, Cristiana Capotondi", "Commedia"],
  ["Non è un paese per vecchi", 2007, "Joel e Ethan Coen", "Javier Bardem, Josh Brolin, Tommy Lee Jones", "Thriller, Western"],
  ["Il petroliere", 2007, "Paul Thomas Anderson", "Daniel Day-Lewis, Paul Dano", "Drammatico"],
  ["Into the Wild - Nelle terre selvagge", 2007, "Sean Penn", "Emile Hirsch, Kristen Stewart", "Avventura, Biografico"],
  ["Ratatouille", 2007, "Brad Bird", "Patton Oswalt (voce)", "Animazione"],
  ["Juno", 2007, "Jason Reitman", "Elliot Page, Michael Cera", "Commedia, Drammatico"],
  ["Il cavaliere oscuro", 2008, "Christopher Nolan", "Christian Bale, Heath Ledger, Aaron Eckhart", "Azione, Thriller"],
  ["WALL·E", 2008, "Andrew Stanton", "Ben Burtt (voce)", "Animazione, Fantascienza"],
  ["Gran Torino", 2008, "Clint Eastwood", "Clint Eastwood, Bee Vang", "Drammatico"],
  ["The Millionaire", 2008, "Danny Boyle", "Dev Patel, Freida Pinto", "Drammatico"],
  ["Gomorra", 2008, "Matteo Garrone", "Toni Servillo, Gianfelice Imparato", "Crime, Drammatico"],
  ["Il divo", 2008, "Paolo Sorrentino", "Toni Servillo", "Biografico, Drammatico"],
  ["In Bruges - La coscienza dell'assassino", 2008, "Martin McDonagh", "Colin Farrell, Brendan Gleeson, Ralph Fiennes", "Commedia nera, Crime"],
  ["Hereditary - Le radici del male", 2018, "Ari Aster", "Toni Collette, Alex Wolff", "Horror"],
  ["Bastardi senza gloria", 2009, "Quentin Tarantino", "Brad Pitt, Christoph Waltz, Mélanie Laurent", "Guerra, Azione"],
  ["Avatar", 2009, "James Cameron", "Sam Worthington, Zoe Saldana", "Fantascienza, Avventura"],
  ["Up", 2009, "Pete Docter", "Ed Asner (voce)", "Animazione, Avventura"],
  ["District 9", 2009, "Neill Blomkamp", "Sharlto Copley", "Fantascienza"],
  ["Il profeta", 2009, "Jacques Audiard", "Tahar Rahim, Niels Arestrup", "Crime, Drammatico"],
  ["Una notte da leoni", 2009, "Todd Phillips", "Bradley Cooper, Ed Helms, Zach Galifianakis", "Commedia"],
  ["Inception", 2010, "Christopher Nolan", "Leonardo DiCaprio, Joseph Gordon-Levitt, Marion Cotillard", "Fantascienza, Azione"],
  ["The Social Network", 2010, "David Fincher", "Jesse Eisenberg, Andrew Garfield", "Biografico, Drammatico"],
  ["Il discorso del re", 2010, "Tom Hooper", "Colin Firth, Geoffrey Rush", "Biografico, Drammatico"],
  ["Toy Story 3 - La grande fuga", 2010, "Lee Unkrich", "Tom Hanks, Tim Allen (voci)", "Animazione"],
  ["Il cigno nero", 2010, "Darren Aronofsky", "Natalie Portman, Mila Kunis", "Thriller, Drammatico"],
  ["Shutter Island", 2010, "Martin Scorsese", "Leonardo DiCaprio, Mark Ruffalo", "Thriller, Mistero"],
  ["Benvenuti al Sud", 2010, "Luca Miniero", "Claudio Bisio, Alessandro Siani", "Commedia"],
  ["Rubber", 2010, "Quentin Dupieux", "Stephen Spinella, Roxane Mesquida, Wings Hauser, Jack Plotnick", "Horror, Commedia nera, Fantasy"],
  ["Drive", 2011, "Nicolas Winding Refn", "Ryan Gosling, Carey Mulligan", "Thriller, Noir"],
  ["Quasi amici", 2011, "Olivier Nakache, Éric Toledano", "François Cluzet, Omar Sy", "Commedia, Drammatico"],
  ["The Artist", 2011, "Michel Hazanavicius", "Jean Dujardin, Bérénice Bejo", "Commedia, Muto"],
  ["Una separazione", 2011, "Asghar Farhadi", "Payman Maadi, Leila Hatami", "Drammatico"],
  ["Midnight in Paris", 2011, "Woody Allen", "Owen Wilson, Marion Cotillard", "Commedia, Fantasy"],
  ["Django Unchained", 2012, "Quentin Tarantino", "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio", "Western"],
  ["Il cavaliere oscuro - Il ritorno", 2012, "Christopher Nolan", "Christian Bale, Tom Hardy, Anne Hathaway", "Azione"],
  ["Argo", 2012, "Ben Affleck", "Ben Affleck, Bryan Cranston", "Thriller, Storico"],
  ["The Avengers", 2012, "Joss Whedon", "Robert Downey Jr., Chris Evans, Scarlett Johansson", "Azione, Supereroi"],
  ["Vita di Pi", 2012, "Ang Lee", "Suraj Sharma, Irrfan Khan", "Avventura, Drammatico"],
  ["Amour", 2012, "Michael Haneke", "Jean-Louis Trintignant, Emmanuelle Riva", "Drammatico"],
  ["Skyfall", 2012, "Sam Mendes", "Daniel Craig, Javier Bardem, Judi Dench", "Azione, Spy"],
  ["La grande bellezza", 2013, "Paolo Sorrentino", "Toni Servillo, Carlo Verdone, Sabrina Ferilli", "Drammatico"],
  ["The Wolf of Wall Street", 2013, "Martin Scorsese", "Leonardo DiCaprio, Jonah Hill, Margot Robbie", "Biografico, Commedia"],
  ["Gravity", 2013, "Alfonso Cuarón", "Sandra Bullock, George Clooney", "Fantascienza, Thriller"],
  ["12 anni schiavo", 2013, "Steve McQueen", "Chiwetel Ejiofor, Michael Fassbender, Lupita Nyong'o", "Storico, Drammatico"],
  ["Her", 2013, "Spike Jonze", "Joaquin Phoenix, Scarlett Johansson (voce)", "Fantascienza, Romantico"],
  ["Prisoners", 2013, "Denis Villeneuve", "Hugh Jackman, Jake Gyllenhaal", "Thriller"],
  ["Interstellar", 2014, "Christopher Nolan", "Matthew McConaughey, Anne Hathaway, Jessica Chastain", "Fantascienza"],
  ["Grand Budapest Hotel", 2014, "Wes Anderson", "Ralph Fiennes, Tony Revolori", "Commedia"],
  ["Whiplash", 2014, "Damien Chazelle", "Miles Teller, J.K. Simmons", "Drammatico, Musica"],
  ["Birdman", 2014, "Alejandro González Iñárritu", "Michael Keaton, Emma Stone, Edward Norton", "Commedia nera, Drammatico"],
  ["L'amore bugiardo - Gone Girl", 2014, "David Fincher", "Ben Affleck, Rosamund Pike", "Thriller"],
  ["Boyhood", 2014, "Richard Linklater", "Ellar Coltrane, Patricia Arquette, Ethan Hawke", "Drammatico"],
  ["John Wick", 2014, "Chad Stahelski", "Keanu Reeves", "Azione"],
  ["Smetto quando voglio", 2014, "Sydney Sibilia", "Edoardo Leo, Valerio Aprea", "Commedia"],
  ["Mad Max: Fury Road", 2015, "George Miller", "Tom Hardy, Charlize Theron", "Azione, Fantascienza"],
  ["Revenant - Redivivo", 2015, "Alejandro González Iñárritu", "Leonardo DiCaprio, Tom Hardy", "Avventura, Drammatico"],
  ["Sopravvissuto - The Martian", 2015, "Ridley Scott", "Matt Damon, Jessica Chastain", "Fantascienza"],
  ["Il caso Spotlight", 2015, "Tom McCarthy", "Michael Keaton, Mark Ruffalo, Rachel McAdams", "Drammatico, Giornalismo"],
  ["Inside Out", 2015, "Pete Docter", "Amy Poehler (voce)", "Animazione"],
  ["Ex Machina", 2015, "Alex Garland", "Domhnall Gleeson, Alicia Vikander, Oscar Isaac", "Fantascienza, Thriller"],
  ["Star Wars: Il risveglio della Forza", 2015, "J.J. Abrams", "Daisy Ridley, Adam Driver, Harrison Ford", "Fantascienza, Avventura"],
  ["The Hateful Eight", 2015, "Quentin Tarantino", "Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh", "Western"],
  ["Lo chiamavano Jeeg Robot", 2015, "Gabriele Mainetti", "Claudio Santamaria, Luca Marinelli", "Supereroi, Drammatico"],
  ["Sicario", 2015, "Denis Villeneuve", "Emily Blunt, Benicio del Toro, Josh Brolin", "Thriller, Crime"],
  ["La La Land", 2016, "Damien Chazelle", "Ryan Gosling, Emma Stone", "Musical, Romantico"],
  ["Arrival", 2016, "Denis Villeneuve", "Amy Adams, Jeremy Renner", "Fantascienza"],
  ["Manchester by the Sea", 2016, "Kenneth Lonergan", "Casey Affleck, Michelle Williams", "Drammatico"],
  ["Perfetti sconosciuti", 2016, "Paolo Genovese", "Marco Giallini, Valerio Mastandrea, Kasia Smutniak", "Commedia, Drammatico"],
  ["Moonlight", 2016, "Barry Jenkins", "Mahershala Ali, Trevante Rhodes", "Drammatico"],
  ["Captain Fantastic", 2016, "Matt Ross", "Viggo Mortensen", "Drammatico, Commedia"],
  ["Quo vado?", 2016, "Gennaro Nunziante", "Checco Zalone", "Commedia"],
  ["Your Name.", 2016, "Makoto Shinkai", "", "Animazione, Romantico"],
  ["Dunkirk", 2017, "Christopher Nolan", "Fionn Whitehead, Tom Hardy, Kenneth Branagh", "Guerra"],
  ["Blade Runner 2049", 2017, "Denis Villeneuve", "Ryan Gosling, Harrison Ford, Ana de Armas", "Fantascienza"],
  ["Chiamami col tuo nome", 2017, "Luca Guadagnino", "Timothée Chalamet, Armie Hammer", "Drammatico, Romantico"],
  ["Tre manifesti a Ebbing, Missouri", 2017, "Martin McDonagh", "Frances McDormand, Sam Rockwell, Woody Harrelson", "Drammatico, Commedia nera"],
  ["La forma dell'acqua", 2017, "Guillermo del Toro", "Sally Hawkins, Doug Jones, Michael Shannon", "Fantasy, Romantico"],
  ["Scappa - Get Out", 2017, "Jordan Peele", "Daniel Kaluuya, Allison Williams", "Horror, Thriller"],
  ["Coco", 2017, "Lee Unkrich", "Anthony Gonzalez (voce)", "Animazione"],
  ["It", 2017, "Andy Muschietti", "Bill Skarsgård, Jaeden Martell", "Horror"],
  ["Bohemian Rhapsody", 2018, "Bryan Singer", "Rami Malek, Lucy Boynton", "Biografico, Musica"],
  ["A Star Is Born", 2018, "Bradley Cooper", "Bradley Cooper, Lady Gaga", "Drammatico, Musica"],
  ["Roma", 2018, "Alfonso Cuarón", "Yalitza Aparicio, Marina de Tavira", "Drammatico"],
  ["Green Book", 2018, "Peter Farrelly", "Viggo Mortensen, Mahershala Ali", "Drammatico, Commedia"],
  ["Avengers: Infinity War", 2018, "Anthony e Joe Russo", "Robert Downey Jr., Josh Brolin, Chris Hemsworth", "Azione, Supereroi"],
  ["Dogman", 2018, "Matteo Garrone", "Marcello Fonte, Edoardo Pesce", "Crime, Drammatico"],
  ["Spider-Man: Un nuovo universo", 2018, "Bob Persichetti, Peter Ramsey, Rodney Rothman", "Shameik Moore (voce)", "Animazione, Supereroi"],
  ["La favorita", 2018, "Yorgos Lanthimos", "Olivia Colman, Emma Stone, Rachel Weisz", "Storico, Commedia nera"],
  ["A Quiet Place - Un posto tranquillo", 2018, "John Krasinski", "Emily Blunt, John Krasinski", "Horror, Thriller"],
  ["Parasite", 2019, "Bong Joon-ho", "Song Kang-ho, Choi Woo-shik", "Thriller, Drammatico"],
  ["Joker", 2019, "Todd Phillips", "Joaquin Phoenix, Robert De Niro", "Drammatico, Thriller"],
  ["C'era una volta a... Hollywood", 2019, "Quentin Tarantino", "Leonardo DiCaprio, Brad Pitt, Margot Robbie", "Commedia, Drammatico"],
  ["1917", 2019, "Sam Mendes", "George MacKay, Dean-Charles Chapman", "Guerra"],
  ["Avengers: Endgame", 2019, "Anthony e Joe Russo", "Robert Downey Jr., Chris Evans, Scarlett Johansson", "Azione, Supereroi"],
  ["Storia di un matrimonio", 2019, "Noah Baumbach", "Adam Driver, Scarlett Johansson", "Drammatico"],
  ["Cena con delitto - Knives Out", 2019, "Rian Johnson", "Daniel Craig, Ana de Armas, Chris Evans", "Giallo, Commedia"],
  ["Jojo Rabbit", 2019, "Taika Waititi", "Roman Griffin Davis, Scarlett Johansson", "Commedia, Guerra"],
  ["Il traditore", 2019, "Marco Bellocchio", "Pierfrancesco Favino", "Biografico, Crime"],
  ["Tenet", 2020, "Christopher Nolan", "John David Washington, Robert Pattinson", "Fantascienza, Azione"],
  ["Nomadland", 2020, "Chloé Zhao", "Frances McDormand", "Drammatico"],
  ["The Father - Nulla è come sembra", 2020, "Florian Zeller", "Anthony Hopkins, Olivia Colman", "Drammatico"],
  ["Soul", 2020, "Pete Docter", "Jamie Foxx, Tina Fey (voci)", "Animazione"],
  ["Un altro giro", 2020, "Thomas Vinterberg", "Mads Mikkelsen", "Drammatico, Commedia"],
  ["Volevo nascondermi", 2020, "Giorgio Diritti", "Elio Germano", "Biografico, Drammatico"],
  ["Dune", 2021, "Denis Villeneuve", "Timothée Chalamet, Zendaya, Rebecca Ferguson", "Fantascienza"],
  ["È stata la mano di Dio", 2021, "Paolo Sorrentino", "Filippo Scotti, Toni Servillo", "Drammatico"],
  ["Il potere del cane", 2021, "Jane Campion", "Benedict Cumberbatch, Kirsten Dunst", "Drammatico, Western"],
  ["Drive My Car", 2021, "Ryusuke Hamaguchi", "Hidetoshi Nishijima", "Drammatico"],
  ["Spider-Man: No Way Home", 2021, "Jon Watts", "Tom Holland, Zendaya", "Azione, Supereroi"],
  ["La persona peggiore del mondo", 2021, "Joachim Trier", "Renate Reinsve", "Drammatico, Romantico"],
  ["Freaks Out", 2021, "Gabriele Mainetti", "Claudio Santamaria, Aurora Giovinazzo", "Fantasy, Storico"],
  ["Everything Everywhere All at Once", 2022, "Daniel Kwan, Daniel Scheinert", "Michelle Yeoh, Ke Huy Quan, Jamie Lee Curtis", "Fantascienza, Commedia"],
  ["Top Gun: Maverick", 2022, "Joseph Kosinski", "Tom Cruise, Miles Teller", "Azione"],
  ["Gli spiriti dell'isola", 2022, "Martin McDonagh", "Colin Farrell, Brendan Gleeson", "Commedia nera, Drammatico"],
  ["Avatar - La via dell'acqua", 2022, "James Cameron", "Sam Worthington, Zoe Saldana", "Fantascienza, Avventura"],
  ["Niente di nuovo sul fronte occidentale", 2022, "Edward Berger", "Felix Kammerer", "Guerra"],
  ["Le otto montagne", 2022, "Felix van Groeningen, Charlotte Vandermeersch", "Luca Marinelli, Alessandro Borghi", "Drammatico"],
  ["Triangle of Sadness", 2022, "Ruben Östlund", "Harris Dickinson, Woody Harrelson", "Commedia nera"],
  ["The Batman", 2022, "Matt Reeves", "Robert Pattinson, Zoë Kravitz", "Azione, Noir"],
  ["Oppenheimer", 2023, "Christopher Nolan", "Cillian Murphy, Robert Downey Jr., Emily Blunt", "Biografico, Storico"],
  ["Barbie", 2023, "Greta Gerwig", "Margot Robbie, Ryan Gosling", "Commedia, Fantasy"],
  ["Povere creature!", 2023, "Yorgos Lanthimos", "Emma Stone, Mark Ruffalo, Willem Dafoe", "Fantasy, Commedia nera"],
  ["Killers of the Flower Moon", 2023, "Martin Scorsese", "Leonardo DiCaprio, Lily Gladstone, Robert De Niro", "Crime, Storico"],
  ["Anatomia di una caduta", 2023, "Justine Triet", "Sandra Hüller, Swann Arlaud", "Drammatico, Giallo"],
  ["La zona d'interesse", 2023, "Jonathan Glazer", "Christian Friedel, Sandra Hüller", "Storico, Drammatico"],
  ["Past Lives", 2023, "Celine Song", "Greta Lee, Teo Yoo", "Drammatico, Romantico"],
  ["C'è ancora domani", 2023, "Paola Cortellesi", "Paola Cortellesi, Valerio Mastandrea", "Drammatico, Commedia"],
  ["Io capitano", 2023, "Matteo Garrone", "Seydou Sarr, Moustapha Fall", "Drammatico"],
  ["The Holdovers - Lezioni di vita", 2023, "Alexander Payne", "Paul Giamatti, Da'Vine Joy Randolph", "Commedia, Drammatico"],
  ["Dune - Parte due", 2024, "Denis Villeneuve", "Timothée Chalamet, Zendaya, Austin Butler", "Fantascienza"],
  ["The Brutalist", 2024, "Brady Corbet", "Adrien Brody, Guy Pearce, Felicity Jones", "Drammatico"],
  ["Anora", 2024, "Sean Baker", "Mikey Madison", "Commedia, Drammatico"],
  ["Conclave", 2024, "Edward Berger", "Ralph Fiennes, Stanley Tucci", "Thriller"],
  ["The Substance", 2024, "Coralie Fargeat", "Demi Moore, Margaret Qualley", "Horror"],
  ["Challengers", 2024, "Luca Guadagnino", "Zendaya, Josh O'Connor, Mike Faist", "Drammatico, Sport"],
  ["A Complete Unknown", 2024, "James Mangold", "Timothée Chalamet, Edward Norton", "Biografico, Musica"],
  ["Vermiglio", 2024, "Maura Delpero", "Tommaso Ragno, Giuseppe De Domenico", "Drammatico"],
  ["Parthenope", 2024, "Paolo Sorrentino", "Celeste Dalla Porta, Gary Oldman", "Drammatico"],
  ["Flow - Un mondo da salvare", 2024, "Gints Zilbalodis", "", "Animazione"],
  ["I peccatori", 2025, "Ryan Coogler", "Michael B. Jordan", "Horror, Drammatico"],
  ["Weapons", 2025, "Zach Cregger", "Julia Garner, Josh Brolin, Alden Ehrenreich, Amy Madigan", "Horror, Mistero, Thriller"],
  ["F1 - Il film", 2025, "Joseph Kosinski", "Brad Pitt, Damson Idris", "Azione, Sport"],
  ["Una battaglia dopo l'altra", 2025, "Paul Thomas Anderson", "Leonardo DiCaprio, Sean Penn", "Thriller, Commedia nera"],
  ["Frankenstein", 2025, "Guillermo del Toro", "Oscar Isaac, Jacob Elordi", "Gotico, Drammatico"],
  ["Avatar - Fuoco e cenere", 2025, "James Cameron", "Sam Worthington, Zoe Saldana", "Fantascienza, Avventura"],
  ["Hamnet", 2025, "Chloé Zhao", "Jessie Buckley, Paul Mescal", "Drammatico, Storico"],
  ["Backrooms", 2026, "Kane Parsons", "Chiwetel Ejiofor, Renate Reinsve, Mark Duplass", "Horror, Fantascienza, Thriller"],
];

const dbPath = process.env.DATABASE_PATH ?? "./data/serate.db";
fs.mkdirSync(path.dirname(dbPath), { recursive: true });
const db = new Database(dbPath);
db.pragma("journal_mode = WAL");
migrate(drizzle(db), { migrationsFolder: path.join(process.cwd(), "db", "migrations") });

const insert = db.prepare(
  "INSERT OR IGNORE INTO movies (title, year, director, actors, genres) VALUES (?, ?, ?, ?, ?)"
);
const insertClassic = db.prepare(
  "INSERT OR IGNORE INTO movies (title, year, director, actors, genres, runtime, synopsis, synopsis_source) VALUES (?, ?, ?, ?, ?, ?, ?, NULL)"
);
let added = 0;
for (const { title, year, director, actors, genres, runtime, synopsis } of CLASSIC_FILMS) {
  const res = insertClassic.run(title, year, director || null, actors || null, genres || null, runtime, synopsis);
  added += res.changes;
}
for (const [title, year, director, actors, genres] of FILMS) {
  const res = insert.run(title, year, director || null, actors || null, genres || null);
  added += res.changes;
}
const total = CLASSIC_FILMS.length + FILMS.length;
console.log(`Catalogo: ${added} film aggiunti (${total - added} già presenti).`);
